### ISSUE TITLE
[Libretro] graphic glitches when using rewind and threaded video

### ISSUE THREAD

**Issue by xTMODx** [LIJI32/SameBoy#110]
I am getting graphical glitches when releasing the rewind button and threaded video setting on when i quickload the glitch is away again until i rewind again
https://www.youtube.com/watch?v=78_15NhEhPs
also when disabling VSYNC it crash when i try to rewind
I am using the newest nightly 1.7.4 64bit and latest core on my Galaxy Note 8

**Comment by LIJI32** [comment]
Duplicate of #42 and libretro/RetroArch#6382 – this bug seems to be in RetroArch's code.
