### ISSUE TITLE
[Question] Start game from terminal?

### ISSUE THREAD

**Issue by rm-code** [LIJI32/SameBoy#124]
Is it possible to start SameBoy with a specific cartridge directly from the terminal?

Would be neat for development as you could simply add something like
```
SameBoy.app/Contents/MacOS/SameBoy -o $GAME
```
to a bash script.

**Comment by LIJI32** [comment]
You can use the `open` terminal command, for example `open -a SameBoy.app rom.gb`. Reopen if `open` is not enough.

**Comment by rm-code** [comment]
Thank you that's exactly what I was looking for 👍
