### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by mddrill** [LIJI32/SameBoy#13]
Hi, is there a way to lower the volume on here? If not, is there a constant I can change in the code to permanently lower it?

**Comment by LIJI32** [comment]
On the current master, you can change MAX_CH_AMP here: https://github.com/LIJI32/SameBoy/blob/master/Core/apu.h#L10
SameBoy 0.9.x has a differently named constant.
But what's the use case?

**Comment by mddrill** [comment]
I was trying to listen to a youtube video and the game music at the same time. The game music was significantly louder than the video.

This should help though, thanks.

As a follow up question, where are the saved game files stored? If I delete the build file and recompile the project, they wont get deleted, right?

Also, I'm concerned with this comment: `Divides nicely and never overflows with 4 channels and 8 volume levels`

It seems to imply that not just any constant will work, it has to divide nicely and not overflow with 4 channels and 8 volume levels, no?

**Comment by LIJI32** [comment]
As long as it's lower than 0x2000 it's fine. Values that do not divide will simply get rounded down.

**Comment by mddrill** [comment]
Thanks. What about the saved game files? Are they stored anywhere or are they part of the .gbc file?

**Comment by mddrill** [comment]
Nevermind. I found it in the game folder. It's a .sav file
