### ISSUE TITLE
(SDL) No sound with SameBoy

### ISSUE THREAD

**Issue by orbea** [LIJI32/SameBoy#130]
OS: `Slackware64-current`
SameBoy: 969fb5a9d8f4804a8848a2bc29b4069df21bb61c
alsa: `alsa-lib-1.1.7`

When running the standalone SameBoy version there is no audio with any games, I tested both gb and gbc roms. I tested all the audio filters and muting and unmuting sound with `ctrl+m` without any changes. I also tried older releases where I recall sound working and found it no longer did. So I suspect the change happened outside of SameBoy, maybe in alsa?

I'm not sure how to get more helpful debugging output, any ideas? Sound still works in the libretro port.

**Comment by LIJI32** [comment]
I actually suspect SDL, the recent versions have audio broken on both Mac and Linux (but not Windows for some reason) under some configurations. What SDL version are you using?

**Comment by orbea** [comment]
I suspect it might not be SDL2, I tested `2.0.8`, `2.0.7` and `2.0.6` without any improvement. I think I had either `2.0.7` or `2.0.8` when I first tried the SDL sameboy frontend.

**Comment by LIJI32** [comment]
What happens if you replace
``` #if SDL_COMPILEDVERSION >= 2005 && defined(__APPLE__) ```
with
``` #if 1 ```
and try again?

**Comment by orbea** [comment]
That did it, now sound works with the most recent `SDL2-2.0.9`.

**Comment by LIJI32** [comment]
As I thought. The guys at SDL claimed they fixed this bug, but they never actually did... =/ I'll just enable this workaround for everything but Windows =/

**Comment by orbea** [comment]
Maybe the fix could be sitting in some branch or even their master and hasn't made it to a release yet? I'm not sure how SDL2 releases work, but thanks for the help!

**Comment by LIJI32** [comment]
The fix was supposed to be in 2.0.6 =/

**Comment by orbea** [comment]
Oh, I guess finding out what happened to their fix would be a good idea...

**Comment by LIJI32** [comment]
If you ever find out what happened to that fix, let me know so I can remove this hack :)
