### ISSUE TITLE
[Feature/Setting Request] Can Sameboy have Super Game Boy (both 1 & 2) emulation support?

### ISSUE THREAD

**Issue by John-Enigma** [LIJI32/SameBoy#132]
Title. 

I know that the Super Game Boy is a peripheral for the Super NES, but wouldn't it be nice if we had that kind of support for Sameboy? It would be nice to play with those art borders. 

I know that BGB also has Super Game Boy support. 

I just thought that it would be nice to make it as a nice addition.

**Comment by John-Enigma** [comment]
@LIJI32

**Comment by LIJI32** [comment]
Incoming in SameBoy 0.12: https://twitter.com/liji32/status/1066296457626558464

**Comment by John-Enigma** [comment]
YES!
