### ISSUE TITLE
Pocket Monsters Crystal Graphic Error

### ISSUE THREAD

**Issue by circularfreezing** [LIJI32/SameBoy#136]
This issue seems to only pop up in the Japanese version of Crystal, because I tested both revisions of the English version and it didn't happen, but if you choose to play as a boy, save and reset then your trainer menu and in battle sprite will be colored blue like you picked the girl. And if you pick the girl, save and reset then the same problems will happen and your overworld sprite will also become a blue boy like in the last screenshot.

https://i.imgur.com/C2qD3rP.png

Edit: I didn't want to clutter up the issue section so I'll just put these here too (also they're not really 'issues')

1. Are there plans for link cable support? Like trading in Pokemon. It's not currently in, right? Because unless I'm missing something two instances of the emulator running just time out when I try to.

2. When you open this emulator by associating it with a file type, settings like controls won't be applied unless you bring up the menu once. It's only really just a minor inconvenience having to press escape twice anytime you open something this way, but would it be possible to have the settings somehow auto applied without having to?

3. Any plans to add cheat code support?

4. Would there be any way to let the emulator fully save without closing it? One time I accidentally lost progress because I opened another game without closing the emulator.

**Comment by LIJI32** [comment]
1. Link cable is, technically, emulated, but actual netplay support is currently only available in the libretro/RetroArch port. Netplay support in the Cocoa and SDL ports is planned for v0.12.
2. Which exact settings are bugged? Are these only controls? Keyboards or joypad? what OS? Please open an issue for that.
3. Yes, planned for v0.13.
4. What do you mean by fully save?

**Comment by circularfreezing** [comment]
By fully save I mean that your progress won't actually be written to the .sav file unless you close the emulator. Say you loaded another rom without closing the emulator first or your computer accidentally shuts down, even if you saved in game it wont affect the .sav file and you'll lose progress. This is all on Windows if that helps.
