### ISSUE TITLE
Compilation error: sgb_boot.asm

### ISSUE THREAD

**Issue by lpla** [LIJI32/SameBoy#140]
Hi. I pulled latest code after several weeks and tried to compile it with my Macbook Pro and `make` shows this error:

```
cd BootROMs && rgbasm -o ../build/bin/BootROMs/sgb_boot.bin.tmp ../BootROMs/sgb_boot.asm
ERROR: ../BootROMs/sgb_boot.asm(85):
    syntax error
error: Assembly aborted in pass 1 (1 errors)!
make: *** [build/bin/BootROMs/sgb_boot.bin] Error 1
```

That line contains `ldh [c], a`

**Comment by LIJI32** [comment]
Update to the latest version of rgbds, this should fix it

**Comment by lpla** [comment]
You are right. I was using latest release of `rgbds` installed using
```
brew install rgbds
```

instead of `master` branch code. Compilation now works with
```
brew install rgbds --HEAD
```

Also, I had to `brew unlink rgbds` before last command to switch between versions, in case anyone finds this helpful.
