### ISSUE TITLE
Aevilia HDMA test

### ISSUE THREAD

**Issue by ISSOtm** [LIJI32/SameBoy#147]
Aevilia's HDMA test fails since [this commit](https://github.com/LIJI32/SameBoy/commit/612cd07fb3203aa61e5c2ce36d68973e41612533).
I've written a test ROM: https://github.com/ISSOtm/EmuDetect
IIRC it only passes on AGB models, however.

**Comment by sczther** [comment]
Duplicate of #32

**Comment by LIJI32** [comment]
@ISSOtm Correct me if I'm wrong, doesn't your test only pass when used with an EverDrive?

**Comment by ISSOtm** [comment]
Likely, I remember it was determined there was some catch, and this is likely it.
