### ISSUE TITLE
question about color correction

### ISSUE THREAD

**Issue by fryshopper** [LIJI32/SameBoy#149]
Hi, curious about how the gamma conversion table for "correct curves" was computed? Is it safe to use in other console / handheld emulators?

I put this same table into snes9x and now it looks remakably different for games like Zelda 3 (night time) - no washed out milky blacks. Reminds me of how some CRTs looked in RGB mode.

**Comment by LIJI32** [comment]
It's a simple gaussian curve (Not a gamma function), with a bit of manual tweaking to compensate for rounding errors. As for other consoles, I think a gamma function would work better for CRT displays, and a slightly more linear curve for LCD displays, but I'm in no way an expert on this topic.
