### ISSUE TITLE
Feature request: undo in the debugger

### ISSUE THREAD

**Issue by NieDzejkob** [LIJI32/SameBoy#156]

**Comment by LIJI32** [comment]
Can you elaborate when you mean by undo?

**Comment by NieDzejkob** [comment]
At the time I thought it was unambiguous, but now I see that it can be understood in a multitude of ways. In fact, I can see two useful ones.

One of the things I have found myself needing is the ability to revert to the state from before executing a command. For example, I once had to debug a graphical glitch that only appeared in some frames. I could step frame-by-frame by breaking on VBlank, but when the problem shows up, the code has already executed. In the end, I decided to switch to bgb and force my way through with save states.

Note that this was impossible in SameBoy because pressing Ctrl+C and then Ctrl+Shift+1 will load the save state *after* execution continues. This might be related to how the window does not refresh when the emulator is paused.

Another feature that could be called "undo" is [reverse debugging](https://www.gnu.org/software/gdb/news/reversible.html). While that sounds like a greater investment, it also seems that it could be more useful. There's also a set of usecases common between both features; I don't know how large this set is.

**Comment by LIJI32** [comment]
Reverse debugging is very hard to achieve in SameBoy, as stepping back all the different state machines is very tricky. Undoing debugger commands, on the other hand, is much easier and can be done using save states. I'll add it to the 0.12 todo list.
