### ISSUE TITLE
Incompatible banked RAM mapping for achievements in libretro (CGB)

### ISSUE THREAD

**Issue by rzumer** [LIJI32/SameBoy#157]
Please see [this issue](https://github.com/meleu/RetroArch-problematic-cheevos/issues/39) for reproduction.

It seems like the memory in the banked RAM area (0xD000~0xDFFF) behaves differently from what is expected. Looking at the descriptors being defined in `libretro.c` they look correct at first glance, but as mentioned in the aforementioned issue the contents in memory do not correspond to the expected state, which results in triggers firing when they should not.

Note that it is the current loaded bank that must be pointed to in the map. From what I can tell, SameBoy is pointing to the first bank at all times. I believe that this is the cause of the compatibility issues. Here is the [reference map](https://github.com/RetroAchievements/RAIntegration/blob/master/src/data/ConsoleContext.cpp#L107).

**Comment by trinemark** [comment]
Was just looking at this also earlier but for RA KDL1.
https://github.com/LIJI32/SameBoy/issues/48

Above analysis is correct. D000 (RAM bank x) is not being mapped correctly for either DMG / CGB modes. And 4000 (ROM bank x) somtimes also although I guess it's less used.

I think Sameboy needs more GB_direct_access_t types to handles this correctly.

**Comment by rzumer** [comment]
Oh wow, sorry I did not notice that issue. Glad I could help pin down the issue.

**Comment by trinemark** [comment]
I think I got it. Unlocked Green Scenery for Kirby's Dream Land in both GB/C modes. I'll test Lucky Luke also to be sure.

Reorganized the descs a bit and using 9 of them atm.
```
descs[2].ptr   = GB_get_direct_access(&gameboy[i], GB_DIRECT_ACCESS_RAM, &size, &bank);
descs[2].start = 0xC000;
descs[2].len   = 0x1000;

descs[3].ptr   = descs[2].ptr + (bank * 0x1000);
descs[3].start = 0xD000;
descs[3].len   = 0x1000;

..

descs[6].ptr   = GB_get_direct_access(&gameboy[i], GB_DIRECT_ACCESS_ROM, &size, &bank);
descs[6].start = 0x0000;
descs[6].len   = 0x4000;
descs[6].flags = RETRO_MEMDESC_CONST;

descs[7].ptr   = descs[6].ptr + (bank * 0x4000);
descs[7].start = 0x4000;
descs[7].len   = 0x4000;
descs[7].flags = RETRO_MEMDESC_CONST;
```
