### ISSUE TITLE
Feature request: Game directory at the start

### ISSUE THREAD

**Issue by John-Enigma** [LIJI32/SameBoy#160]
@LIJI32 

Can we have an option to browse for our ROMs, instead of Dragging & Dropping a ROM to play? 

And while that's happening, can the directory be saved, just so the next we close/restart the emulator, the directory stays there?

Now that I think about it, I don't even know if this emulator has a config file.

EDIT: This is what I mean (and for the record, I'm taking BlastEm [Sega Genesis emulator by Mask_of_Destiny aka Mike Pavone] as an example): 

1. The initial for when you load a ROM, or deal with the settings and what not. The Load ROM option is where you browse for the files. ![blasteminitroom](https://user-images.githubusercontent.com/22717497/55761986-10413500-5a16-11e9-8596-379fdbfc6855.PNG)

2. The ROM directory. Is pretty self-explanatory. ![blastemromdirectory](https://user-images.githubusercontent.com/22717497/55761993-159e7f80-5a16-11e9-951a-4f18c765a67e.PNG)

**Comment by LIJI32** [comment]
Will probably won't make it to 0.12's release, but I'll add it to 0.13's todo list

**Comment by LIJI32** [comment]
Added a platform-dependent file open dialog to the SDL port (Cocoa on Mac, WinAPI on Windows, GTK on everything else (when available)).
