### ISSUE TITLE
libretro crash on load when achievements are enabled with some titles

### ISSUE THREAD

**Issue by rzumer** [LIJI32/SameBoy#162]
Encountered with "Harry Potter and the Sorcerer's Stone", using the 64-bit Windows version just after @trinemark's PR #158 was merged (so this is not related to #159). I use the GBC bootloader and the crash occurs immediately on load. RetroArch log is not useful at all, there is no error message displayed.

When achievements are disabled, configuration saved and RetroArch restarted, I can launch without an issue, so I think it may be related to the memory descriptors. I don't think that there is enough time to log in and fetch data from the RetroAchievements server before the crash occurs. Other GB and GBC titles that I tested can boot correctly, so it is not a straightforward issue from my perspective. I did not try booting this title in SameBoy before, so I am not sure when the issue started happening, and #158 is not necessarily related.

I also tested other libretro cores that support achievements (Gambatte and Gearboy) and have no problem with those. They have the same memory map as SameBoy currently.

I'm not sure if memory can be accessed before being initialized, see https://github.com/libretro/gambatte-libretro/commit/1a037ec8fc1f68b213925ee1e05ff6cf1bdb5df6 for an example of how to avoid that.

**Comment by trinemark** [comment]
Tried it but couldn't get a crash with Sameboy and Nintendo BIOS. If you can compile the code, try this:
https://github.com/LIJI32/SameBoy/blob/master/libretro/libretro.c#L1055
```
void *retro_get_memory_data(unsigned type)
{
	if (!initialized)
		return 0;

	void *data = NULL;
```

https://github.com/LIJI32/SameBoy/blob/master/libretro/libretro.c#L1120
```
size_t retro_get_memory_size(unsigned type)
{
	if (!initialized)
		return 0;

	size_t size = 0;
```

**Comment by rzumer** [comment]
I don't have an environment set up to build libretro binaries right now, but a silent crash somewhere in the achievements processing pipeline related to the memory info does seem very likely. Looking at the log again, it is clear that the system is loaded partway, but cuts off suddenly with no error output.

**Comment by rzumer** [comment]
Works well, @trinemark. I think this fix can be PRed for safety, but it is likely a symptom of a [RetroArch issue](https://github.com/libretro/RetroArch/issues/8582) where the achievements system fetches the memory info too early and expects it to never change.

**Comment by rzumer** [comment]
A freshly-compiled (debug) build works without an issue, but that's irrelevant of whether the fix is applied or not.

When fetching a core update from the RetroArch updater, it crashes again.

**Comment by rzumer** [comment]
See the comments of the RetroArch issue linked to this one. I may look into it after the CGB RAM size is adjusted.

**Comment by rzumer** [comment]
I have no idea when this was solved, but the latest version no longer appears to crash, so closing.

It is possible that the CGB RAM size update solved it.
