### ISSUE TITLE
Why is RAM size on CGB larger than expected?

### ISSUE THREAD

**Issue by rzumer** [LIJI32/SameBoy#165]
Based on a few sources, the GB/C memory map has one fixed RAM bank (or bank 0) and another bank that is fixed for GB and one of seven banks on GBC. As expected, RAM size is set to 0x2000 in GB mode, but GBC allocates twice the expected size. Why is that, and can you please describe how is memory laid out in SameBoy in practice?

My purpose for asking this question is to figure out what implications this has on libretro memory mapping, but it would also be nice to document this as general information, since it does not seem to be standard practice.

**Comment by LIJI32** [comment]
Wow, that's a silly mistake that got carried since pre-0.1 days. It also affects the save state size and rewinding CPU/memory usage. I'll fix it in for 0.12 while retaining compatibility with older save states.
