### ISSUE TITLE
MIDI over the link port

### ISSUE THREAD

**Issue by tommitytom** [LIJI32/SameBoy#169]
I've been building a libretro frontend that acts as a VST instrument, with SameBoy as my main focus for now.  The bulk of the work is done, all that is remaining is sending MIDI over the link port, for software like LSDJ and mGB (there is similar chat going on in issue https://github.com/LIJI32/SameBoy/issues/18).  

Now, I have the MIDI functionality working, but it's very laggy, and I think it's due to how I'm sending the bytes to SameBoy. I can seemingly send one byte to the link port for every call to `retro_run`, and since a MIDI message consists of 3 bytes, it takes 3 calls to `retro_run` before the full message is received, which is obviously creating massive delays between notes.  Am I misunderstanding how the link port operates, or is there some way of sending multiple bytes per call to `retro_run`?

**Comment by tommitytom** [comment]
OK maybe I asked that question prematurely.. I realise I should be using `GB_run` instead of `GB_run_frame`!

**Comment by cyberic99** [comment]
@tommitytom wow that is a great idea!

And that could be transposed to other emulators too.

Do you already have some code ready?

**Comment by tommitytom** [comment]
I've got it working with mGB and LSDJ and it's AWESOME!  However, due to the way VST plugins are loaded in to the same process, it doesn't play too well with libretro (which only allows a single instance).  As a result I've been building my own emulator wrapper that contains streams timed link port and controller data (so I can eventually support genMDM).  Code will be up once that's done :)

**Comment by cyberic99** [comment]
cool!

What is the benefit of using libretro rather than the native SameBoy ?

**Comment by LIJI32** [comment]
Yes, you probably want to send bytes much faster than only once per frame. Also keep in mind that if the MIDI port is the serial master, you can send bytes in whatever rate you want, as long as the Game Boy software processes them quickly enough. Any more issues or can I close this issue?

**Comment by tommitytom** [comment]
I found that sending 1 bit every ~488 ticks didn't work, but sending a whole byte every ~3907 ticks works great!
