### ISSUE TITLE
Feature Request: Add hotkeys for showing the Console, Memory, and VRAM Viewer on macOS

### ISSUE THREAD

**Issue by daltonclaybrook** [LIJI32/SameBoy#170]
Each time I load a ROM, I open one or more of these windows as well. It would be nice to have a hotkey to use.

**Comment by LIJI32** [comment]
macOS has a built in feature that lets you assign shortcuts to any app via System Preferences > Keyboard > Shortcuts > App Shortcuts. Isn't this good enough?

**Comment by daltonclaybrook** [comment]
Oh wow, I had no idea you could do this. That's perfect, thanks!
