### ISSUE TITLE
Chiki Chiki Machine Mou Race (Japan) missing hud

### ISSUE THREAD

**Issue by GrieverV** [LIJI32/SameBoy#185]
There should be a HUD on the bottom of the screen, instead you can only see the top of the map part of the HUD (the black bar).  

SameBoy:  
![SameBoy - Chiki Chiki Machine Mou Race (Japan)](https://user-images.githubusercontent.com/38054248/59971899-b9e28d80-9552-11e9-8002-66a1370e269f.png)  

BGB:  
![BGB - Chiki Chiki Machine Mou Race (Japan)](https://user-images.githubusercontent.com/38054248/59971910-dd0d3d00-9552-11e9-8797-c09f79bd6a68.png)  

Reported in mgba-emu/mgba#1345

**Comment by LIJI32** [comment]
Fixed on master with the new window implementation.
