### ISSUE TITLE
Razor Freestyle Scooter (USA) graphic glitches

### ISSUE THREAD

**Issue by GrieverV** [LIJI32/SameBoy#186]
At the bottom of the screen where the HUD should be during gameplay, there's just garbled graphics.  

SameBoy:  
![SameBoy - Razor Freestyle Scooter (USA)](https://user-images.githubusercontent.com/38054248/59971962-d6cb9080-9553-11e9-8b78-19707b2ad4e1.png)  

BGB:  
![BGB - Razor Freestyle Scooter (USA)](https://user-images.githubusercontent.com/38054248/59971970-e519ac80-9553-11e9-9a2c-935aeea2e13b.png)  

Reported in mgba-emu/mgba#1346

**Comment by LIJI32** [comment]
Fixed on master with the new window implementation.
