### ISSUE TITLE
Link's Awakening DX (JP 1.0) ACE Failure

### ISSUE THREAD

**Issue by spicefather** [LIJI32/SameBoy#188]
One of the speedrun categories for LADX is Any% ACE (arbitrary code execution). By setting our filenames in a specific way and following certain steps, we're able to skip to the end-game cutscene.
As a test of fitness for allowing SameBoy for speedrunning, I've tested this route several times but am entirely unable to reproduce the intended effects.

Upon opening the chest at the end of the run, the effects see are either:
- game freezes
- game crashes (black screen in SameBoy)

The game freeze is an expected outcome -- it happens sometimes if a certain value in RAM isn't "good". However the crash is something which doesn't occur elsewhere (BGB 1.5.7, Gambatte Speedrun r649, or on Gameboy Player).

I've attached two states:
1: file select screen with file names already input
0: near end of run, just before opening the final chest

You can also find the current world record video [here](https://www.youtube.com/watch?v=8pLQVoi3aME) for a demo of what should happen. If you're trying to follow along, bear in mind that everything needs to be followed identically (especially filenames and talking to the child on the way back from the beach).
[ACE.zip](https://github.com/LIJI32/SameBoy/files/3393500/ACE.zip)

Thanks for your time.

**Comment by LIJI32** [comment]
This will surely take some work, but I hope I can get it fixed soon. Is there any documentation on how this ACE works? It should aid in fixing this bug.

**Comment by spicefather** [comment]
I'll try to get more detailed information as I can. The most I'm familiar with is that code in the region of 0xF600 (echo of 0xD600 -- filename storage) is executed as part of it.

**Comment by spicefather** [comment]
With the help of other people pointing out me doing something wrong in my tests, I was able to get this to work. Sorry for wasting your time. :(
