### ISSUE TITLE
[Libretro] Broken sound

### ISSUE THREAD

**Issue by orbea** [LIJI32/SameBoy#189]
OS: `Slackware64-current`
sameboy: https://github.com/LIJI32/SameBoy/commit/9f7255cd239c55af4356d76e22e1c57d20c164ba
retroarch: `1.7.7`

With the SameBoy master and the recent `0.12.1` stable all sound in the libretro core is broken and will have have white noise and stuttering. This affects both gb and gbc games and starts as soon as the bios screen shows.

The SDL2 version of SameBoy is not affected.

I tried to bisect this and it failed.

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
8b7922b6798ef51288e5400e7a2e78ab810656d4
b2397a2e7a25e1f451a389671889c771d4c3b570
083b4a2970fe514e23e2e23927b682322299c578
66b814a226c596faf14ac6c1522bb52413e8d454
e268efefeff5720a6a3ae29a7b88283849c05076
We cannot bisect more!
```

8b7922b6798ef51288e5400e7a2e78ab810656d4
b2397a2e7a25e1f451a389671889c771d4c3b570
083b4a2970fe514e23e2e23927b682322299c578
66b814a226c596faf14ac6c1522bb52413e8d454
e268efefeff5720a6a3ae29a7b88283849c05076

This is also a blocker for updating SameBoy to `0.12.1` on Slackware for me.

**Comment by orbea** [comment]
I redid the bisect applying the Makefile fix.

https://github.com/LIJI32/SameBoy/commit/e268efefeff5720a6a3ae29a7b88283849c05076#diff-691980c178164b2b1492e2ba21780987R15

```
e268efefeff5720a6a3ae29a7b88283849c05076 is the first bad commit
commit e268efefeff5720a6a3ae29a7b88283849c05076
Author: Lior Halphon <LIJI32@gmail.com>
Date:   Sat Jun 15 23:22:27 2019 +0300

    Redesign and reimplement the audio API, let the frontends handle more stuff. Probably affects #161

 Cocoa/Document.m         | 69 ++++++++++++++++++++++++++++++++++++++-
 Core/apu.c               | 84 ++++++++----------------------------------------
 Core/apu.h               | 18 ++++-------
 Core/debugger.c          | 42 ++++++++++++------------
 Core/gb.c                |  3 --
 Core/gb.h                |  2 +-
 Core/memory.c            |  4 +--
 Core/sgb.c               | 25 +++++++++-----
 Core/sgb.h               |  1 -
 Core/timing.c            |  6 ++--
 SDL/main.c               | 19 +++++------
 libretro/Makefile.common |  1 +
 libretro/libretro.c      | 21 +++---------
 13 files changed, 146 insertions(+), 149 deletions(-)
```
e268efefeff5720a6a3ae29a7b88283849c05076

**Comment by LIJI32** [comment]
Weird, it tested it on RetroArch for macOS and it worked. I can see why this change would break things as I redid the way I report audio to RetroArch, but it still seems like a RetroArch bug. I can try to work around it.

**Comment by orbea** [comment]
I looked closer and on my system this only affects the `alsa` and `oss` (aoss) audio drivers while the alsathread, tinyalsa, openal and SDL2 audio drivers play sound correctly. I do not have pulseaudio installed so I can not check that one.

**Comment by LIJI32** [comment]
I suspected that was a driver issue. I think I have a workaround, I'll try it tomorrow.

**Comment by orbea** [comment]
I tried to look at this closer with printf and I think the issue is related to this function and line.

https://github.com/libretro/RetroArch/blob/127bf556c7db243c635d8cc117735f8317e0db7b/audio/drivers/alsa.c#L225

Before your change the `size` condition for the while loop is consistently true each time the function runs, but after your change its only true every few times it runs.

I also neglected to mention that this issue negatively affects the fps too.

**Comment by retro-wertz** [comment]
im on the same boat as orbea. using alsa. switched to pulse no difference. libretro's port which is older still has problem

1st bad commit: https://github.com/LIJI32/SameBoy/commit/e268efefeff5720a6a3ae29a7b88283849c05076
- and that because thats the only one i can compile from the last working commit : https://github.com/LIJI32/SameBoy/commit/5a04054145e7215c5afe74cce1fb35b3a50bab26

**Comment by LIJI32** [comment]
@max-m already confirmed that the issue is caused by calling `audio_batch_cb((void*)sample, 1)` instead of `audio_sample_cb((void*)sample->left, (void*)sample->right)`, as I suspected. They should be equivalent, but turns out they're not on some audio drivers. I'll commit the fix later today.

**Comment by orbea** [comment]
@LIJI32 Thank you! I can confirm the fix works here too. I'll submit an update for SameBoy on slackbuilds.org today. :)
