### ISSUE TITLE
RFE: Record to RIFF WAVE (.wav)

### ISSUE THREAD

**Issue by pinobatch** [LIJI32/SameBoy#192]
VBA-M, mGBA, and BGB can record emulated audio to an uncompressed RIFF WAVE file. I'd like to see this feature added to SameBoy, as SameBoy's audio emulation is more accurate than BGB's with respect to noise LFSR lockup.

**Comment by theofficialgman** [comment]
I have seen this requested by other users as well. would be a nice edition

**Comment by LIJI32** [comment]
Has been added in 0.15.
