### ISSUE TITLE
Link's Awakening DX - Timing Issues

### ISSUE THREAD

**Issue by spicefather** [LIJI32/SameBoy#193]
SameBoy appears to be faster when compared to BGB in some situations. I tested LADX by entering and leaving the starting house 20 times (a total of 40 warps), and SameBoy can be clearly seen as performing more quickly from the very beginning.

I have created a video comparing the two emulators: https://youtu.be/pHK9gj6C5bA (excuse my bad video editing skills)
SameBoy is top-left, BGB is bottom right. The test was done on most recent versions of each emulator using the Japanese 1.0 ROM of LADX, and simply holding up/down during the fade to activate warps as early as the game allows.

For note, I did a similar comparison with overworld screen transitions, and there was no noticeable speed difference.

**Comment by LIJI32** [comment]
Are you certain that's a SameBoy bug and not a BGB bug? What about Gambatte? Also, which "flavor" of SameBoy is that, Cocoa, SDL or RetroArch?

**Comment by spicefather** [comment]
This is on SDL version. I'm trying to get a video of console test as well, but I can't record one myself unfortunately. Will test Gambatte tonight when I'll able.

**Comment by spicefather** [comment]
I tested Gambatte-Speedrun r649, and I see the same pull-ahead for SameBoy. Still pending a console video but I'll let you know once I have one.

**Comment by spicefather** [comment]
[Here](https://www.youtube.com/watch?v=FoStvC7Mans) is a comparison with GBI (bottom-left) also included. It seems to be identical to BGB.

**Comment by carmiker** [comment]
This issue also has implications for audio latency. Add this line:
printf("%d\n", SDL_GetQueuedAudioSize(device_id));
to SDL/audio/sdl.c on line 64 and observe as the queue size spikes upon entering or exiting a building. Other transitions also induce similar spikes, such as starting from a saved game.

**Comment by daid** [comment]
Timing issues seem to be related to the fact that LADX disables the LCD during screen transitions to load graphics data. If I remove that disable it messes up all graphics, but it no longer shows timing issues.

My guess is that Sameboy rounds up the time spend with the LCD off to a full frame time to keep the frame rate towards the "host" system constant?
