### ISSUE TITLE
Feature Request: Cheat Support

### ISSUE THREAD

**Issue by teconmoon** [LIJI32/SameBoy#194]
Hi there,

Thinking this is probably out-of-scope for an emulator that focuses on accuracy, but I am requesting cheat code support for this emulator.

The reason I am requesting this is that I recently started using the WideGB fork, and would like to utilize the Pokemon Gold cheat codes to walk anywhere and avoid random battles so that I can flesh out the widescreen scenes for said title.

Anyways, if cheat code support of our-of-scope for SameBoy feel free to close this. Thanks for reading!

**Comment by LIJI32** [comment]
It's not out-of-scope, and is already scheduled for SameBoy 0.14. :)

**Comment by LIJI32** [comment]
Added for 0.13's upcoming release (Cocoa only)
