### ISSUE TITLE
Liberto Core update to 0.12.1

### ISSUE THREAD

**Issue by iGom** [LIJI32/SameBoy#197]
Since Jun 22, the emulator was updated with several improvements and it would be interesting to update the core of libretro as well which is 0.11.2 at the moment

**Comment by LIJI32** [comment]
The 0.12.1 libretro core should already be available; if it's not, open an issue at [libretro's fork of SameBoy](https://github.com/libretro/SameBoy), as the libretro team is responsible for binary releases of the core.

**Comment by LIJI32** [comment]
The libretro fork just re-enabled issues, you can report it now if you haven't done that somewhere else already.

**Comment by iGom** [comment]
gonna do it, thanks!
