### ISSUE TITLE
Libretro Core fails to copy the right file for iOS

### ISSUE THREAD

**Issue by jet082** [LIJI32/SameBoy#198]
As it says in the title. It is seeming to try to copy ``sameboy_libretro_ios.dylib`` in the root of the build directory, but the file itself is present as ``build/bin/sameboy_libretro_ios.dylib``

This leads to the following error:

```
cp "sameboy_libretro_ios.dylib" "/Users/chucksmith/retroarch-stuff/libretro-super/dist/ios-arm64/sameboy_libretro_ios.dylib"
cp: sameboy_libretro_ios.dylib: No such file or directory
```

However, the compiled file is present and works fine. It is just in an unexpected place.

**Comment by LIJI32** [comment]
The libretro build system is maintained by the libretro team, you should report this issue at  [libretro's fork of SameBoy](https://github.com/libretro/SameBoy).
