### ISSUE TITLE
Custom DMG BootRom WaitBFrames is very innacurate

### ISSUE THREAD

**Issue by fattard** [LIJI32/SameBoy#20]
I was writing my own custom bootrom code, and got the quick animation based on your source code.
When checking wait for frames, I found this code to be not accurate to count frames

```assembly
WaitFrame:
    ldh a, [$44]
    cp $90 ; <-- compares LY=144, if LY is already 144, it will return early
    jr nz, WaitFrame
    ret

WaitBFrames:
    call WaitFrame
    dec b ; <-- while LY=144, frame checks will be skipped
    jr nz, WaitBFrames 
    ret
```

As you may notice, calling WaitBFrames while LY is still 144 will drop all the additional waits you were expecting. If you are lucky, LY increases to 145 and another frame will be correctly awaited.

As you are a guy very paranoid for accuracy, I can suggest the implementation I used for the WaitFrame :)

```assembly
WaitFrame:
    ldh a, [$44]
    cp 143 ; <-- syncs to a new frame first
    jr nz, WaitFrame
wait_ly_144:
    ldh a, [$44]
    cp 144 ; <-- now we can wait for vblank
    jr nz, wait_ly_144
    ret
```

The above code will always work in WaitBFrames, because LY=144 now, we need a new frame in LY=143
(maybe the first sync frame will be dropped, but we have a little time while LY increments)
With this new code, calling WaitBFrames(60) will wait for a sec correctly.

And now to fix the animation timings based on the new function, giving it an entire duration of about 1 sec, without cutting sound off too early:

```assembly
; Wait ~0.08 seconds
    ld b, 5 ; <-- just enough time to display logo
    call WaitBFrames

    ; Play first sound
    ld a, $83
    call PlaySound
    ld b, 5 ; <-- wait for ~ 0.084 sec, almost the original tone duration
    call WaitBFrames
    ; Play second sound
    ld a, $c1
    call PlaySound

; Wait ~0.9 seconds
    ld b, 50 ; <-- wait for a sec to let tone finishes playing 
    call WaitBFrames
```

I applied those changes to my own custom boot [here](https://github.com/fattard/xFF/blob/gb/emu/CutomBootROM/DMG/DMG_CustomBootRom.asm)

Thank you for your efforts on getting pretty accurate emulation! Maybe I will need help later with audio emulation, as I have zero knowledge about digital audio processing, except maybe I know a .wav file stores waves :)

**Comment by LIJI32** [comment]
Nice catch, this silly bug has been around since v0.1! The funny thing is that the CGB boot ROM has a completely different implementation that doesn't suffer from this issue. I'll just use that implementation instead. :)
