### ISSUE TITLE
Imposible open emulator 0xc000007b

### ISSUE THREAD

**Issue by tetradog** [LIJI32/SameBoy#200]
i'm using Windows 10

**Comment by aaaaaa123456789** [comment]
0xC000007B (`STATUS_INVALID_IMAGE_FORMAT`) indicates that the .exe is corrupt.

**Comment by LIJI32** [comment]
Redownload the file and try again? Seems like a corrupt download.

**Comment by tetradog** [comment]
I tried old version but still corrupt...

**Comment by cremno** [comment]
There are other possibilities, e.g. sameboy.exe loading a x64 SDL2.dll.

You can use a tool like [Dependencies](https://github.com/lucasg/Dependencies#installation-and-usage) to find out if that's the case.

**Comment by LIJI32** [comment]
Quite weird considering nobody else encountered this issue. Are you sure your zip software is extracting SameBoy correctly? What's the exactly size, in bytes, of `sameboy.exe` after extracting it?
