### ISSUE TITLE
No High-DPI support under Windows

### ISSUE THREAD

**Issue by Marat-Tanalin** [LIJI32/SameBoy#202]
Though High DPI display support is stated in the readme, SameBoy apparently does not support HiDPI (High DPI) at least under Windows.

For HiDPI support, a Windows application should:

* declare itself as DPI-aware;
* take OS-level zoom (e.g. 200%) into account when rendering the app’s user interface.

DPI-awareness may be declared either statically or dynamically. A static declaration consists of a `<dpiAware>true</dpiAware>` XML element in the application manifest — this is the way recommended by Microsoft. Dynamic declaration can be done by calling either `SetProcessDPIAware()` (Windows Vista/7/8) or `SetProcessDpiAwareness()` (Windows 8.1+) WinAPI functions before creating any windows.

Neither of these are present in SameBoy.

The screenshot below shows SameBoy in two different modes on a 4K monitor at 200% OS-level zoom:

* left: the default one — with DPI scaling automatically applied by Windows to applications not declared as DPI-aware;

* right: with DPI-awareness _forced_ via executable-file properties (`*.exe` properties → Compatibility → Change high DPI settings → Override high DPI scaling behavior. Scaling performed by → Application). As a result, the app is not automatically scaled by Windows, and while the app does not scale itself, it has the same size in physical pixels as at OS-level zoom of 100%, and so effectively smaller proportionally than should be at the actual non-100% zoom.

![sameboy-dpi-aware](https://user-images.githubusercontent.com/1833563/65367035-64db1400-dc34-11e9-85c2-63b02be5bf1f.png)

Thanks.

**Comment by SatoMew** [comment]
> DPI-awareness may be declared either statically or dynamically. A static declaration consists of a `<dpiAware>true</dpiAware>` XML element in the application manifest

That applies to [older Windows only](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware). On newer Windows, you must use `<dpiAwareness>PerMonitorV2, unaware</dpiAwareness>` ([more info](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiawareness)).

It's better to link Liji to official documentation as well as third-party and reliable information, such as:

- https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows
- https://kynosarges.org/WindowsDpi.html

**Comment by Marat-Tanalin** [comment]
Per-monitor declaration only makes sense if the app _actually_ supports it, which is rare. I briefly described _basic_ support which is typically enough. Also, the `dpiAwareness` element is not supported by Windows older than 10, so the basic declaration is needed _anyway_. Thanks for the addition.

**Comment by SatoMew** [comment]
> Per-monitor declaration only makes sense if the app _actually_ supports it, which is rare.

Per-monitor scaling was added in Windows 8.1 and is used by default since then so an app that only declares itself as system DPI aware is limiting itself to how the scaling works on Windows Vista, 7, and 8. That seems counterproductive as most users of Windows that also benefit from DPI scaling are probably using Windows 8.1 or 10 anyhow due to the technical improvements made to the scaling mechanisms.

To properly declare the awareness statically and support all Windows versions, one must use `<dpiAware>true/PM</dpiAware>` instead of `<dpiAware>true</dpiAware>`, in addition to `<dpiAwareness>PerMonitorV2, unaware</dpiAwareness>`, which will override the former if present and the app is run on a compatible Windows version.

[Here's an official Windows blog article](https://blogs.windows.com/windowsdeveloper/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/) explaining the current state of DPI scaling, which was followed up by [this addendum](https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/).

Given that older Windows is on life support or already EOL'd, I wonder if the initial focus shouldn't be on current Windows first, especially since Liji might not prefer to use Windows as an OS, in which case there are [gratis development VMs](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) available.

**Comment by LIJI32** [comment]
Quite amusing, considering high DPI works perfectly on my Windows 7 VM:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/2345928/65976499-e0c92d80-e478-11e9-85f1-d4e5312e0c10.png">

Will calling `SetProcessDPIAware` do the work? I'm not sure what application manifests are, and I'd rather avoid adding more Windows-specific stuff to the build, considering how fragile these tools are across different build environments.

**Comment by SatoMew** [comment]
> Will calling `SetProcessDPIAware` do the work? I'm not sure what application manifests are, and I'd rather avoid adding more Windows-specific stuff to the build, considering how fragile these tools are across different build environments.

On current Windows, [`SetProcessDpiAwareContext`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) should be used in favor of [`SetProcessDpiAware`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness). In either case, Microsoft advises against programmatically defining DPI awareness, recommending [manifests](https://en.wikipedia.org/wiki/Manifest_file) instead. These manifest files are XML-based and are essentially metadata for the app that is either embedded into its executable file or appended externally via a `.manifest` file ([this](https://walbourn.github.io/manifest-madness/) also shows how you may end up with too much of it).

**Comment by LIJI32** [comment]
I can't use `SetProcessDpiAwareContext` because I'm still supporting Windows 7. Are these manifests basically yet-another-resource, or are they something else?

**Comment by SatoMew** [comment]
Manifests are yet another resource. Since you already use Visual Studio, you just have to select Application Manifest File in the Add item dialog and adjust it accordingly.

Windows 8 and earlier use only Windows XP style scaling by default which is equivalent to DPI unawareness, hence your screenshot. If you disable it on Windows 7 to also enable Windows Vista style scaling instead ([how-to](https://kynosarges.org/images/dpi/Win7CustomSettings.png)), the SameBoy UI will probably behave differently.

**Comment by LIJI32** [comment]
I'm not using Visual Studio, I only use the Windows SDK together with Clang and MSVC's linker, but it should be just as easy if it's just a resource.

**Comment by SatoMew** [comment]
Oh, my bad, I was going off the README.md since it mentions Visual Studio as a requirement.

**Comment by Marat-Tanalin** [comment]
> Quite amusing, considering high DPI works perfectly on my Windows 7 VM

Windows sometimes automatically disables DPI virtualization (DPI scaling) for specific applications. See the checkbox “Disable display scaling on high DPI settings” (“Compatibility” tab → “Settings” section) in properties of the executable — the checkbox is probably checked.

This is how SameBoy 0.12.2 looks under Windows 7 Home Premium on a physical computer at 200% OS-level zoom:

![sameboy-w7-dpi-aware](https://user-images.githubusercontent.com/1833563/65988248-23e2cb00-e490-11e9-8e26-e69828e2c186.png)

> Will calling `SetProcessDPIAware` do the work?

Yes, it’s equivalent to a static declaration in manifest. Note that it only _declares_ DPI awareness, while you should scale/resize UI on your own according to pixel density/ratio. Afaict, SameBoy is already capable of scaling its UI given that its window is resizable, so what’s left is to declare SameBoy as DPI-aware and set the default scale according to DPI. I determine scaling ratio this way:

	// USER_DEFAULT_SCREEN_DPI is 96
	double getPixelRatio() {
		HDC  hdc = GetDC(NULL);
		UINT dpi = GetDeviceCaps(hdc, LOGPIXELSX);

		ReleaseDC(NULL, hdc);

		return (double)dpi / (double)USER_DEFAULT_SCREEN_DPI;
	}

> Are these manifests basically yet-another-resource, or are they something else?

An application manifest is an XML file embedded as a resource in the application’s executable file. See [documentation](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests) on MS site for details.

**Comment by Marat-Tanalin** [comment]
As a side note, even aside from blurriness (Windows 7) or pixelation (Windows 10 at integer OS-level zooms) caused by automatic DPI scaling, an important aspect of DPI awareness specifically in terms of _integer scaling_ is that it allows to use screen space _more entirely_.

For example, Game Boy’s screen height is 144 pixels, which results in a ratio of **7.5** on a Full&nbsp;HD (1920×1080) display (6.7% of the height [0.5 of 7.5] are lost and filled with black when integer scaling is enabled) and exactly **15** on a 4K (3840×2160) display (**no** height is lost at all).

If an app is not declared as DPI-aware, it effectively works by default at a virtual resolution lower-than-native proportionaly with OS-level zoom. So on a 4K display at 200%, the app works as if the display was Full&nbsp;HD, so 6.7% of the height are unreasonably lost by default even on 4K displays.

**Comment by LIJI32** [comment]
All this logic should already be there, as the SDL port is DPI aware on Linux and macOS.  A call to `SetProcessDPIAware` should probably work then.

**Comment by SatoMew** [comment]
> This is how SameBoy 0.12.2 looks under Windows 7 Home Premium on a physical computer at 200% OS-level zoom:
> 
> ![sameboy-w7-dpi-aware](https://user-images.githubusercontent.com/1833563/65988248-23e2cb00-e490-11e9-8e26-e69828e2c186.png)

Is this with exclusive Windows XP style scaling enabled or disabled?

**Comment by Marat-Tanalin** [comment]
Why are you asking? Regular scaling, never used the “Use Windows XP style DPI scaling” checkbox, always kept it unchecked as it is by default. The screenshot just shows that results under W7 and&nbsp;W10 are basically the same (except for window style and DPI-scaling-related blur under W7).
