### ISSUE TITLE
Feature request: A border for games when not on SGB.

### ISSUE THREAD

**Issue by IdiotBlueMage** [LIJI32/SameBoy#203]
What I'm talking about here is something similar to bgb's custom borders.  It can load a bmp file and use it as a border of the same dimensions as the SGB default, basically making everything you run have the same appearance.  SGB borders replace it when it is turned on.  If a custom one can't be done, another option is a setting to enable the SGB or SGB2 default border to appear when not in SGB mode.

This would be handy for especially those on mobile in Libretro.  Everything would then be in the same form factor no matter which system is emulated, making it easier for getting video settings correct on certain screen sizes.

**Comment by LIJI32** [comment]
This feature is available in the SDL and Cocoa ports, not yet in the libretro one. (Closed by mistake)
