### ISSUE TITLE
Super Game Boy graphical glitches

### ISSUE THREAD

**Issue by SMG456** [LIJI32/SameBoy#208]
Every time I try to play Super Game Boy games on SameBoy 0.12.2 it results in the window being glitched. Even replacing the SameBoy BIOS ROMs with Nintendo's official BIOS ROMs doesn't fix this.

I am using Windows 7 Service Pack 1 (32-bit).

(nevermind the Windows Classic theme and Windows 98 color scheme)

![Glitch!](https://user-images.githubusercontent.com/27364420/67030941-7e119c00-f0de-11e9-8b0c-535f1eab3188.png)

**Comment by LIJI32** [comment]
What GPU are you using?

**Comment by LIJI32** [comment]
And does changing the scaling filter have any effect when emulating different models?

**Comment by SMG456** [comment]
> What GPU are you using?
It's an Intel HD Graphics (Sandy Bridge) iGPU.

**Comment by SMG456** [comment]
> And does changing the scaling filter have any effect when emulating different models?

I've tried changing it, and unfortunately, no effect.

**Comment by LIJI32** [comment]
Well this means you GPU does not support OpenGL 3.2 (You might want to try updating your drivers, OpenGL 3.2 is very old by now, and older than Sandy Bridge itself by a few years), so it falls back to software rendering. It's probably a bug with software rendering.

**Comment by SMG456** [comment]
> Well this means you GPU does not support OpenGL 3.2 (You might want to try updating your drivers, OpenGL 3.2 is very old by now, and older than Sandy Bridge itself by a few years), so it falls back to software rendering. It's probably a bug with software rendering.

You might want to add OpenGL 2.0 rendering.

**Comment by LIJI32** [comment]
OpenGL 2 rendering will not be added. It's ancient it lacks many features that are required for the scaling filters to work. Software rendering however will be fixed to allow SGB to work.

This is, by the way, *very* lousy from Intel's side, as the open source Linux drivers for the very same GPU support OpenGL 3.3.

**Comment by LIJI32** [comment]
This might be applicable for SameBoy on Windows as well, if you want filters working, should serve as a work around until a fixed binary is released:

https://community.citra-emu.org/t/force-opengl3-3-on-intel-hd-graphics-3000-windows/14122
