### ISSUE TITLE
Support for official SGB ROMs

### ISSUE THREAD

**Issue by SMG456** [LIJI32/SameBoy#209]
SameBoy does allow you to replace the bootroms with Nintendo's official versions, but the Super Game Boy SNES ROMs are hardcoded.

Can you add support for Nintendo's official ROMs?
They will be located in the SameBoy installation folder, and will be named:

sgbntsc.sfc = Super Game Boy (NTSC)
sgbpal.sfc = Super Game Boy (PAL)
sgb2.sfc = Super Game Boy 2

**Comment by LIJI32** [comment]
You have the SGB boot ROMs and the SGB BIOSs, which are different things. The former runs on the Game Boy chip inside the SGB cartridge, and the latter runs on the SNES/SFC itself. The boot ROMs provides ares my own, but can be replaced with the official ones. As for BIOSs, none are included, they’re not even hard coded. Instead, they’re high level emulated. SameBoy is not an SNES emulator so it cannot emulate the actual SNES BIOSs. Recent versions of bsnes use SameBoy’s core for SGB emulation while using the bsnes core for the SFC side. If you’re interested in LLE of the SGB, you should use that.
