### ISSUE TITLE
0.12.2 macOS binary requires 10.14, even though minimum appears to be 10.9

### ISSUE THREAD

**Issue by slingshotocelot** [LIJI32/SameBoy#214]
I'm running macOS 10.13.6 High Sierra, and the 0.12.2 release binary of SameBoy does not launch, saying the software requires macOS 10.14. I was able to build a working version 0.12.2 from the source code just fine without making any changes, however. I noticed in Info.plist the minimum system version is listed as 10.9, so this might just be a build target thing with the most recent release.

**Comment by LIJI32** [comment]
Huh, I gave the minimum version flag to the compiler, but not to the linker, so it just assumed my current macOS version.
