### ISSUE TITLE
[Feature Request] GBS File Support

### ISSUE THREAD

**Issue by jprjr** [LIJI32/SameBoy#229]
I'm a big fan of chiptunes and think SameBoy has some of the best sound.

My feature request is for SameBoy to expose a C interface for loading a GBS file (from memory and/or from a file) and rendering audio samples. Doesn't necessarily need a GUI, my goal is to integrate SameBoy into music players (foobar2000, MPD, etc) as a chiptune decoder.

Thank you so much for the emulator!!! It's my new favorite way to play games.

**Comment by lpla** [comment]
For now, you can use the `.gb` output file from [GBS2GB](http://www.angelfire.com/nc/ugetab/GBS2GB117.zip) in Sameboy. Windows only, but should work.

Source: http://www.angelfire.com/nc/ugetab/

**Comment by jprjr** [comment]
That doesn't really allow the goal of integrating with music players, though.

Tried doing some of it myself but it is *way* above my head. I *think* I managed to load up the ROM data manually and I can get it to run a few CPU cycles but I seem to start hitting illegal instructions pretty quickly. I think there's some kind of setup I need to do with registers? It's really not clear from the GBS spec.

**Comment by LIJI32** [comment]
I could swear I replied to that issue before. I can add a GBS API so it can be used as a library. Can't give an ETA on it though.

**Comment by jprjr** [comment]
Closing this out since it's now implemented in v0.14.3
