### ISSUE TITLE
GBC internal color palettes for GB games.

### ISSUE THREAD

**Issue by Arviel** [LIJI32/SameBoy#23]
The GBC had special palettes for several GB games built into the BIOS which would be automatically assigned whenever you would play GB games on a GBC. If no special palette was found, it would then default to one of the generic ones. Is it possible to add this feature to Sameboy? there is already support for external BIOS. Gambatte has a similar feature and it is quite handy.

Maybe an option to toggle which hardware to emulate on boot would be best as that would give you the option of emulating the GB or the GBC when playing original GB games.

[Here](https://buildbot.libretro.com/.docs/library/gambatte/#core-options) is an example of the internal GBC palettes on Gambatte.

Thank you for porting this emulator over to Retroarch by the way, it is awesome!

**Comment by LIJI32** [comment]
SameBoy has this feature since the first v0.1 release, but the libretro core automatically emulates DMG if the file ends with a .gb extension. This should probably be made into an option. Meanwhile, you can bypass this limitation by changing the extension to .gbc.

**Comment by Arviel** [comment]
That worked for me. Thank you! I posted this on the libretro forums as well so other will know of this.
