### ISSUE TITLE
Warau Inu no Bouken - Silly Go Lucky! (Japan) graphic glitch

### ISSUE THREAD

**Issue by sdhizumi** [LIJI32/SameBoy#230]
I found this problems on title demo.

Examples:
![image](https://user-images.githubusercontent.com/31327231/74098103-724b5900-4b57-11ea-89b5-6f120f9d00e5.png)
![image](https://user-images.githubusercontent.com/31327231/74098106-7e371b00-4b57-11ea-82df-c0e137371790.png)

I tested on Sameboy v0.12.3

**Comment by LIJI32** [comment]
Good find, this is a regression introduced almost 2 years ago, in a commit that ironically fixed another regression.
