### ISSUE TITLE
Feature request: debugger: skip-until-end-of-halt

### ISSUE THREAD

**Issue by NieDzejkob** [LIJI32/SameBoy#233]
When the code <s>grinds</s> runs into a `halt`, there's no easy way to skip until the halt period ends. Perhaps `step` should run all the cycles of the halt? OTOH, one might want to debug some LCD or APU behavior cycle by cycle...

`finish` is an option, also.

**Comment by LIJI32** [comment]
`step` and `finish` should remain the same (Single step one M-cycle and run until the current function returns, respectively); `next` should be updated to run until `halt` is done.
