### ISSUE TITLE
[Feature Request] GBA mode for CGB games (Core option)

### ISSUE THREAD

**Issue by SigmaVirus** [LIJI32/SameBoy#24]
As of today there is no way of entering The Advance Shop in Oracle of Ages and Oracle of Seasons in either SameBoy standalone or the Libretro core.

**Oracle of Seasons, The Advance Shop is open**
![image](https://user-images.githubusercontent.com/14175085/34904919-47a5f302-f84f-11e7-8fc4-3d4343658092.png)

**Oracle of Ages, The Advance Shop is open**
![image](https://user-images.githubusercontent.com/14175085/34904922-625d44c0-f84f-11e7-9715-e813a3d63575.png)

It is a unique shop often referred to as the 100 Rupee Advance Shop and can only be accessed when either games is played on a Game Boy Advance console, otherwise the right-sided doors will be closed and shut.

bgb, Gambatte and most other emulators have the option to enable Game Boy Advance mode one way or another.

There isn't a whole lot of CGB games that takes advantage of playing on the GBA and I believe there is only four games that does it.

1. **Oracle of Ages**, The Advance Shop is open
2. **Oracle of Seasons**, The Advance Shop is open
3. **Shantae**, I don't know the exact details on this
4. **Wendy - Every Witch Way**, Three extra levels to play

Thanks in advance!

**Comment by LIJI32** [comment]
Done for the standalone ports (Cocoa and SDL). For the libretro version, it's the same issue as as #23.

**Comment by SigmaVirus** [comment]
@LIJI32 
Does that mean this option is on it's way?

**Comment by Awakened0** [comment]
It'd be good to have an Auto option that uses GameBoy mode for .gb ROMs and Color mode for .gbc like it did before. Right now I have to set GB mode as my default so I get monochrome on those games (to use properly with the GB pocket shader) and I have to make per game overrides for all my GBC games to make them boot in GBC mode.

**Comment by LIJI32** [comment]
Sounds easy enough to add, I'll do it.

**Comment by Awakened0** [comment]
Thanks :D
