### ISSUE TITLE
MBC30 4MB test ROM support

### ISSUE THREAD

**Issue by lpla** [LIJI32/SameBoy#244]
I just built a Pokémon Crystal flashcart (Japanese version) as it contains the MBC30 mapper, which allows up to 4MB ROMs. As of today, no MBC3/MBC30 ROM is bigger than 2MB except a test ROM: https://github.com/EricKirschenmann/MBC3-Tester-gb

Compiled version attached:
[mbctest.gb.zip](https://github.com/LIJI32/SameBoy/files/4394743/mbctest.gb.zip)

Hardware works:
![IMG_4300](https://user-images.githubusercontent.com/1533393/77777514-fb5b1880-704f-11ea-829d-aa98d5061e0d.jpeg)

Sameboy doesn't:
![Captura de pantalla 2020-03-27 a las 17 26 25](https://user-images.githubusercontent.com/1533393/77777615-1a59aa80-7050-11ea-9d8f-a1a30dd48ca8.png)

This ROM test is not passing the last 2MB of the ROM. Also, mGBA and gambatte fail the same way. bgb works.

**Comment by LIJI32** [comment]
Thanks, good timing too as I had this on my TODO list for 0.13. Can you elaborate on the actual difference between MBC3 and MBC30? Is the ROM bank internal register 1 bit smaller on MBC3? Or do they behave the same when you use a 2MB or smaller ROM and try to map bank $80?
