### ISSUE TITLE
Using the assignment operator on a 16-bit dereference (e.g. {$c000}=$6144) only writes the low byte ([$c000]=$44) but not the high byte ([$c001]=whatever it was before)

### ISSUE THREAD

**Issue by Volleo6144** [LIJI32/SameBoy#245]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/38385509/77861156-f1185600-71d8-11ea-86cd-7396e2c51d29.png">

Now, I can understand _returning_ only the low byte (zero-padded to 16 bits), but ...

Again, as in #38, one _can_ use `([hl]=$44)+$100*([hl+1]=$61)` over and over, but I'm pretty sure this is a bug nonetheless.

**Comment by LIJI32** [comment]
Yes, this is a bug; I forgot about assignment when adding {} support.
