### ISSUE TITLE
gcc unrecognized commandline option -Wpartial-availablility

### ISSUE THREAD

**Issue by capnhawkbill** [LIJI32/SameBoy#249]
project doesn't compile and gives multiple errors about the flag -Wpartial-availablility
removing the flag from the makefile fixes it

**Comment by lpla** [comment]
Which OS is this? And `gcc` version?

**Comment by NieDzejkob** [comment]
FWIW, I can reproduce this on Guix with GCC 9.3.0.

**Comment by capnhawkbill** [comment]
I am sorry for not providing the information
I'm running arch linux 9.3.0-1
gcc 9.3.0 (newest i believe)

kernel:
5.6.4-arch1-1
