### ISSUE TITLE
[Regression] [Libretro] Real BootROMs Not Being Used

### ISSUE THREAD

**Issue by Awakened0** [LIJI32/SameBoy#256]
I have cgb_boot.bin and dmg_boot.bin in my System directory, but the Win64 Libretro core I just built isn't seeing them and is using the Sameboy BootROMs when loading a game. A build I did from April 8th still loads them.

**Comment by LIJI32** [comment]
I'll have a look today, it's a very possible regression as I just changed related code.

**Comment by Awakened0** [comment]
Thanks, works fine now.

For some reason I've been getting a NUL file created in the SameBoy source folder after compiling in my msys2 environment. Windows won't let me delete it normally; I have to follow the steps [here](https://stackoverflow.com/questions/17883481/delete-a-file-named-nul-on-windows) to get rid of it. I'm still copying old precompiled BootROMs from the libretro repo to build\bin\BootROMs before building, so I'm not sure if that could be causing it. But it only started happening when I compiled a build yesterday.

**Comment by LIJI32** [comment]
Interestingly this link describes the exact issue:
```Instead of suppressing output it actually created a file named "NUL" in the current directory. (Apparently it expects "/dev/null", even on Windows.)```

I'm just surprised it managed to create a file named `NUL`.
