### ISSUE TITLE
Missing declaration in source code

### ISSUE THREAD

**Issue by FishTheFirst** [LIJI32/SameBoy#260]
I'm having trouble finding the declaration for gb->display_state and gb->display_cycles referenced in several source files. Is this intended?

**Comment by NieDzejkob** [comment]
On Fri, May 22, 2020 at 12:09:35AM -0700, Emanuel Oliveira wrote:
> I'm having trouble finding the declaration for gb->display_state and gb->display_cycles referenced in several source files. Is this intended?

Please study the `GB_UNIT` macro defined in `Core/timing.h`.

**Comment by FishTheFirst** [comment]
Sneaky macro. 👍
