### ISSUE TITLE
Audio (cpu?) slows down when holding select

### ISSUE THREAD

**Issue by stijnfrishert** [LIJI32/SameBoy#265]
I'm using Sameboy mainly for composition using LSDJ (which I hope you're somewhat familiar with).

When I'm playing my music and holding select (mapped to my left shift), all audio playback runs at 50% speed and drops in pitch.

Using macOS Catalina.

**Comment by LIJI32** [comment]
Shift is the default key for slow-motion mode, you can remap it to something else to avoid it.

**Comment by LIJI32** [comment]
Leaving this open because the GUI should at least warn you about it.

**Comment by stijnfrishert** [comment]
Aaaah, that explains a lot! Thanks :)

**Comment by LIJI32** [comment]
Fixed in 0.13.2
