### ISSUE TITLE
Incorrect noise channel PRNG emulation

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#267]
The attached ROM plays a noise sound, altering NR43 register.
On real hardware (tested on DMG), the sound is randomly muted after a while.
In SameBoy, the sound seems to play forever.
[noisebug.zip](https://github.com/LIJI32/SameBoy/files/4766548/noisebug.zip)

**Comment by jkotlinski** [comment]
To clarify why improved emulation would be desired: A piece of music made on Sameboy might sound bad when playing it back on real hardware, due to noise channel cutting off randomly.

**Comment by jkotlinski** [comment]
Attaching another ROM, where noise randomly mutes on DMG by simply writing the same value to NR43_REG twice in a row, with a specific timing:
[noisebug2.gb.gz](https://github.com/LIJI32/SameBoy/files/5767027/noisebug2.gb.gz)

**Comment by LIJI32** [comment]
That's a super interesting finding! CGB-E and D behave just like how SameBoy emulates, while CGB-C and older indeed have these hiccups. I'll have to see how the two ranges of models actually differ.

**Comment by jkotlinski** [comment]
This appears properly emulated now!
