### ISSUE TITLE
Internal palette option suggestions

### ISSUE THREAD

**Issue by RokkumanX** [LIJI32/SameBoy#269]
Hi

I have been on a quest for replicating the DMG, GBL and GBP palettes for over 5 years and finally I feel I'm completely satisfied and what better way would it be sharing my results with you @LIJI32 so maybe you could add it to SameBoy one day?

![Palettes](https://user-images.githubusercontent.com/50436544/84507495-33720f00-acc1-11ea-860a-7e9af0b7eda3.jpg)

This is what my work is based on:

![dmg](https://user-images.githubusercontent.com/50436544/84507600-5d2b3600-acc1-11ea-9aa9-80dfd4a53558.jpg)

![gbl](https://user-images.githubusercontent.com/50436544/84507609-63211700-acc1-11ea-8850-20b41c4f3ae7.jpg)

![gbp](https://user-images.githubusercontent.com/50436544/84507618-687e6180-acc1-11ea-9b25-69784e6ca8bf.jpg)

If you don't want to use these there is no shame in turning it down, it's still an honor using the most accurate Game Boy emulator, thanks for all your hard work!

**Comment by RokkumanX** [comment]
Does anyone have an opinion about this?

**Comment by LIJI32** [comment]
I like the GBP one, the rest have too low contrast IMO. SameBoy's DMG palette is not faithful, but it's the same palette used by the SDL GUI and the CGB boot ROM. I might rename it to "SameBoy" and add a more faithful DMG palette. I do want to add more palette options to SameBoy 0.14, although I'm not sure which.

**Comment by RokkumanX** [comment]
Here is a couple of more suggestions, the Yellow DMG Game Boy one at the right is my own and I swear to god that's not how I remember things at all, the screen must be unhealthy and damaged.

![image](https://user-images.githubusercontent.com/50436544/85249437-09a0b100-b454-11ea-83ae-c307cc60ff85.png)

**Comment by RokkumanX** [comment]
Here is another example

![image](https://user-images.githubusercontent.com/50436544/85249767-f6421580-b454-11ea-8482-abc9de5d43a3.png)

**Comment by RokkumanX** [comment]
Another example

![image](https://user-images.githubusercontent.com/50436544/85250203-31911400-b456-11ea-8804-04c9e5ef4a45.png)

**Comment by RokkumanX** [comment]
Well this is pretty much everything I can come up with honestly.

It's not easy making palettes when all you own is 2 busted DMG Game Boys that have unhealthy screens, it's a lot of guesses and estimates.

Hopefully something here can be of use to you @LIJI32

**Comment by RokkumanX** [comment]
Spent most of my day with this:

![image](https://user-images.githubusercontent.com/50436544/85285092-8ea9bb80-b490-11ea-9b18-022bb8da11b5.png)

**Comment by RokkumanX** [comment]
Just use your imagination, it certainly looks better with these borders so you can visualize it.

![image](https://user-images.githubusercontent.com/50436544/85290865-fadced00-b499-11ea-9de7-5db8c45e4ac6.png)

![image](https://user-images.githubusercontent.com/50436544/85290885-029c9180-b49a-11ea-84c7-cd516dea9e88.png)

![image](https://user-images.githubusercontent.com/50436544/85290903-0af4cc80-b49a-11ea-9320-50a83dd461f4.png)

**Comment by RokkumanX** [comment]
Work based on these

![image](https://user-images.githubusercontent.com/50436544/85293097-26150b80-b49d-11ea-9a9e-7595e04dfc3b.png)

![image](https://user-images.githubusercontent.com/50436544/85293122-2e6d4680-b49d-11ea-9432-04cd922a17fd.png)

![image](https://user-images.githubusercontent.com/50436544/85293146-362ceb00-b49d-11ea-9779-624cf50c7bdf.png)

**Comment by RokkumanX** [comment]
Well this is pretty much everything I can come up with honestly.

It's not easy making palettes when all you own is 2 busted DMG Game Boys that have unhealthy screens, it's a lot of guesses and estimates.

Hopefully something here can be of use to you @LIJI32

**Comment by jkotlinski** [comment]
Just from a quick glance, those palettes seem much closer to reality than any emulator I saw! Well done!

**Comment by RokkumanX** [comment]
Thanks for your feedback @jkotlinski 

I've spent many hours over the years trying to perfect Game Boy palettes and I think I've come to a certain point that I'm done and satisfied with the result.

Anyone can use these palettes whether it be for SameBoy, Gambatte or bgb.
Everything people need is in the Palette Release Candidates picture above.

I really think that Game Boy palettes is as crucial as the emulators, accurate palettes really makes a whole lot of difference for the experience.

Again, thanks for your kind words and may the palettes bring you happiness and memories!

**Comment by RokkumanX** [comment]
If anyone wants to try these palettes out right now they are in the Gambatte Libretro core.

[gambatte_libretro.dll.zip](https://github.com/LIJI32/SameBoy/files/4834694/gambatte_libretro.dll.zip)

Still images is one thing but seeing these in motion is a whole different ball game, just select Internal under GB Colorization and then either GB - DMG, GB - Pocket or GB - Light under Internal Palette.

If you are familiar with Libretro then you can either use or modify it's shaders to use the appropriate Game Boy Borders, pretty much the same I slapped my demo shots in above.

Good luck to anyone who wants to try it out.

**Comment by RokkumanX** [comment]
I made some shaders for the SameBoy Libretro core based on this work, https://github.com/libretro/glsl-shaders/pull/119

That way people have some options to choose from, both Gambatte and SameBoy.

I'm closing this now.
