### ISSUE TITLE
Image process pokemon / linux

### ISSUE THREAD

**Issue by Alfonso-Patdstres** [LIJI32/SameBoy#283]
In the version 13.3 everything worked just fine, but with de version 13.4 a black square shows up 
these is the same rom from an online emulator
![errorweb](https://user-images.githubusercontent.com/66790203/89569062-cd4dc800-d7e9-11ea-8dd5-315afb87a33b.png)
these is from sameboy v 13.4,( same rom) 
![errorsameboy](https://user-images.githubusercontent.com/66790203/89569157-eeaeb400-d7e9-11ea-9408-39c16ec36118.png)
I am using it on linux 
The rest of the game works fine, it just the "animations", in battle is the same.

**Comment by LIJI32** [comment]
I just released 0.13.5, fixing major regressions introduced in 0.13.4; it should work in the latest major.

**Comment by Alfonso-Patdstres** [comment]
All fixed with version0.13.5. thanx
