### ISSUE TITLE
(libretro) changing the Emulated Model may trigger achievements

### ISSUE THREAD

**Issue by Jamiras** [LIJI32/SameBoy#288]
When the various SameBoy splash screens are displayed, the system memory ($C000-$DFFF) seems to temporarily be filled with random garbage. Depending on the complexity of the achievement and what the apparently random data is set to, this can cause achievements to trigger. As we require an achievement to be false before it can trigger, initially starting a game seems to be okay, but changing the Emulated Model causes the splash screen to reappear, during which time the randomized memory may trigger achievements.

I've attached a video illustrating the problem using our standalone frontend where you can see the memory being randomized. The three addresses (two in green, one in red) are associated with the achievement in the lower right. The video starts with the memory in the expected state (zeroed out in this case). The first time I switch models, you can see two of the four conditions for the achievement become active (the number starts counting up in the lower right window). After a few seconds, the memory returns to a zeroed out state. Then I switch models again and the random memory aligns with all four conditions and the achievement triggers. I switch models twice more to illustrate that the memory is not consistent when set to the same model, implying that it is random and not BIOS code or something similar.

[Sameboy-SGB_RAM.zip](https://github.com/LIJI32/SameBoy/files/5212811/Sameboy-SGB_RAM.zip)

Ideally, the memory would be left alone when the switching models (like the cartridge RAM in $A000-$BFFF), or initialized to some consistent state.

**Comment by Jamiras** [comment]
Alternately, if there's some way for the core to tell the frontend that it reset the emulator, we can re-enable the logic that requires the achievement be false before it can trigger.

**Comment by LIJI32** [comment]
Some games rely on uninitialized being random (Such as Worms, which will freeze, for example, if booted with an all-zero RAM). Keeping memory in tact doesn't really make sense, considering different models have different RAM sizes. Maybe the libretro guys have better ideas.

**Comment by Jamiras** [comment]
As there doesn't seem to be any way for the core to notify the frontend of the reset occurring, would it be possible to not automatically reset? If the user manually resets, we should be able to rely on the "must be false before it can trigger" logic which is already used when selecting "Restart Content".

**Comment by Sanaki** [comment]
To be fair, that approach would likely be preferable for the users' experience as well. Accidentally resetting via an option toggle could be quite vexing in the middle of a run.

**Comment by SimpleTease** [comment]
Hi! I created this PR to address this cheevos problem, and help users who accidentally auto-reset their game. And takes care of a few minor problems when libretro resetting.
https://github.com/LIJI32/SameBoy/pull/298

**Comment by Jamiras** [comment]
Verified that the core no longer resets when switching emulated modes.
