### ISSUE TITLE
clang dependency?

### ISSUE THREAD

**Issue by rofl0r** [LIJI32/SameBoy#296]
the README states clang is required. does that mean this project can't be built with another C compiler such as GCC?

**Comment by LIJI32** [comment]
I guess I should clarify the README a bit. Clang is the primary and recommended compiler for SameBoy, and all official releases are compiled with Clang. GCC support, however, is still actively maintained and supported. Other compilers may or may not work and are not explicitly supported.

**Comment by rofl0r** [comment]
ah, glad to hear that. i really dislike clang and won't ever install it on my system due to it being a C++ clusterfuck that takes aeons to compile from source and results in an installation of several 100MBs. also ideologically it seems its main purpose is a corporate takeover of free software infrastructure. anyway let me know when you've updated the README so i can add myself to the "stargazers".
