### ISSUE TITLE
Midtones look too dark

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#297]
![bild](https://user-images.githubusercontent.com/3259963/95402049-0b14bd00-090f-11eb-97b4-b07b227161be.png)

left BGB, which is pretty close to real CGB.
right Sameboy, notice that the text on yellow appears blocky.
this is strange to me, because the color conversion routines in display.c look great when reimplemented in Java or Javascript. is it some shader issue?

**Comment by jkotlinski** [comment]
PR https://github.com/LIJI32/SameBoy/pull/299

**Comment by jkotlinski** [comment]
#299

**Comment by LIJI32** [comment]
I'm pretty sure you just have color correction disabled in your settings? Can you verify?

**Comment by LIJI32** [comment]
Actually, I'm certain it's disabled. This specific shade of green is not something "Emulate Hardware" or "Reduce Contrast" can ever output.

**Comment by jkotlinski** [comment]
Following a thorough investigation, I no longer believe this is a SameBoy problem. Thanks for feedback.
