### ISSUE TITLE
Restore compatibility with bsnes

### ISSUE THREAD

**Issue by rtretiakov** [LIJI32/SameBoy#300]
I have been doing some work on bsnes lately, and it appears that shortly after v0.13.1 was tagged, this change broke compatibility with bsnes:
https://github.com/LIJI32/SameBoy/blob/2a5aed626da3cfe6d8e2adac9116e82a280e93c5/Core/save_state.h#L8

Commit where it broke:
https://github.com/LIJI32/SameBoy/commit/b6b56d07668ae2be6c5d963cdfc1aeb170022dfd

Really it's incompatibility between C11 with GNU extensions, and C++. This simply does not build using clang++ or g++. Below is a sample of one of the many similar errors:
`error: 'GB_gameboy_internal_s::<unnamed union>::<unnamed struct>::<unnamed enum> GB_gameboy_internal_s::<unnamed union>::<unnamed struct>::GB_STANDARD_MBC1_WIRING' invalid; an anonymous struct may only have public non-static data members [-fpermissive]`

I would like to get the version of SameBoy in bsnes back in sync with upstream releases. I can probably do some changes to fix this, but it is probably better if it's done upstream.

**Comment by LIJI32** [comment]
Can you confirm this change fixes it?
Replace:
```
 #define GB_SECTION(name, ...) __attribute__ ((aligned (8))) union {uint8_t name##_section_start; struct {__VA_ARGS__};}; uint8_t name##_section_end[0] 
```
With:
```
#ifdef __cplusplus
#define GB_SECTION(name, ...) __attribute__ ((aligned (8))) __VA_ARGS__
#else
#define GB_SECTION(name, ...) __attribute__ ((aligned (8))) union {uint8_t name##_section_start; struct {__VA_ARGS__};}; uint8_t name##_section_end[0] 
#endif
```

**Comment by rtretiakov** [comment]
@LIJI32 that does fix the build, and everything seems to run okay for me, including saving/loading states.

**Comment by rtretiakov** [comment]
Thank you for taking care of this!
