### ISSUE TITLE
Building with GB_DISABLE_DEBUGGER and/or GB_DISABLE_CHEATS is broken

### ISSUE THREAD

**Issue by Ryzee119** [LIJI32/SameBoy#302]
It creates a lot of build errors 😞 

### GB_DISABLE_DEBUGGER 
This section needs a bit of rework. It's also missing a stub for `GB_debugger_find_symbol`.

https://github.com/LIJI32/SameBoy/blob/919a88ec23f8011dd0389a4abceb62b3d0c83e00/Core/debugger.h#L10-L17
```
expected identifier or '('
void GB_debugger_ret_hook(GB_gameboy_t *gb)
     ^
Core/debugger.h:13:35: note: expanded from macro 'GB_debugger_ret_hook'
#define GB_debugger_ret_hook(gb) (void)0
                                  ^
Core/debugger.c:2039:6: error: expected ')'
Core/debugger.h:13:35: note: expanded from macro 'GB_debugger_ret_hook'
#define GB_debugger_ret_hook(gb) (void)0
                                  ^
... (alot more)
```
### GB_DISABLE_CHEATS 
Error occurs here with due to the way this stub is done:
https://github.com/LIJI32/SameBoy/blob/919a88ec23f8011dd0389a4abceb62b3d0c83e00/Core/cheats.h#L20-L25
```
Core/cheats.c:34:1: error: expected identifier or '('
{
```

**Comment by LIJI32** [comment]
What exactly are you building? These flags are for the libretro port, which don’t compile cheats.c or debugger.c; it doesn’t make sense to compile them with those flags on.

**Comment by Ryzee119** [comment]
Ah my mistake, I am just building using make/clang on Linux. Playing with different build options to disable undeeded features.
