### ISSUE TITLE
RTC testrom doesn't pass

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#307]
Source is here:
https://github.com/aaaaaa123456789/rtc3test
Doesn't pass even the basic tests. Tested on today's source.

**Comment by LIJI32** [comment]
It’s a known issue, RTC docs were incomplete prior to ax6’s test and I didn’t have the hardware to research them myself. RTC support is scheduled to be rewritten for the next release.

**Comment by sczther** [comment]
Basic and range tests now pass in latest master, only sub-second writes are having problems :)

**Comment by LIJI32** [comment]
They all pass if you set the RTC emulation mode to "accurate" instead of "sync to host RTC".
