### ISSUE TITLE
Pulse channel 1 sound not correctly reproduced

### ISSUE THREAD

**Issue by defensem3ch** [LIJI32/SameBoy#309]
Play provided rom + save on hardware DMG vs Sameboy (I tested in v0.13.6 on Linux). BGB reproduces this correctly. Video comparison: https://cdn.discordapp.com/attachments/725446247485538414/779187829770289162/2020-11-19_22-27-33.mp4
[lsdj896.zip](https://github.com/LIJI32/SameBoy/files/5571093/lsdj896.zip)

**Comment by LIJI32** [comment]
I tried it on several different models, and while they all sound the same, they sound nothing like SameBoy nor BGB. They also display completely different things than what I see inside SameBoy or BGB. Might be because I don't have a clue how to use LSDJ and/or my flash cart is being weird.

**Comment by defensem3ch** [comment]
@LIJI32 this sounds much, much closer to BGB to me than Sameboy. What's happening is that LSDJ is setting the software pitch to update once per tick, which is 24 times per beat at 152 beats per minute, with an upward pitch sweep. However the pulse 1 hardware sweep is also enabled with a downward pitch sweep. So the high pitched pulse cycles are interspersed with low pitched pulse cycles. Sameboy doesn't play the hardware sweep at all, and only emulates the upward pitch sweep. I also tested this on a GBA SP 101 and can replicate the sound. I've attached raw audio, here's a link to a video [https://youtu.be/MI52yOjieeM](https://youtu.be/MI52yOjieeM)
[DMG_sweep_recording.zip](https://github.com/LIJI32/SameBoy/files/5578812/DMG_sweep_recording.zip)

**Comment by defensem3ch** [comment]
I've also compiled this into a rom to simplify the playback (no LSDJ usage required). I've tested this on hardware DMG and GBA SP to confirm that it plays differently than Sameboy.
[player.zip](https://github.com/LIJI32/SameBoy/files/5579679/player.zip)

**Comment by LIJI32** [comment]
Yeah, this ROM makes far more sense, must have been my flash cart.
