### ISSUE TITLE
Tester outputs invalid bmp files

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#310]
While the files can be viewed in most image viewers, imagemagick complains:
``./blargg/cpu_instrs.bmp BMP 160x144 160x144+0+0 8-bit sRGB 92230B 0.000u 0:00.000
identify: length and filesize do not match `./blargg/cpu_instrs.bmp' @ error/bmp.c/ReadBMPImage/854.
``
Fixing this would allow to automate regression testing.

**Comment by LIJI32** [comment]
For compatibility with current (internal and public) testing infrastructure, I kept the (standard, but not as widely supported as you'd expect) `.bmp` format the same, but added a `--tga` option that uses a (more standard and compatible) `.tga` file instead.
