### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by MrPlayerYork** [LIJI32/SameBoy#312]
hey, when I went to download the emulator, my computer blocked it for having a trojan..
version: 0.13.6

**Comment by LIJI32** [comment]
Assuming this is Windows Defender, this is a false positive. Because Microsoft will not fix this false positive, SameBoy for Windows is no longer maintained. You can (try to) disable Windows Defender and send your complaints to Microsoft.

**Comment by LIJI32** [comment]
Or in other words – your "Anti malware" solution is a malware by itself and there's nothing I can do about it =/

**Comment by LIJI32** [comment]
More on the series:
https://github.com/LIJI32/SameBoy/issues/287
https://twitter.com/liji32/status/1317176198619893761
https://twitter.com/liji32/status/1316739743388971010
https://twitter.com/liji32/status/1316141239629160454
