### ISSUE TITLE
Problems with Super JetPak DX

### ISSUE THREAD

**Issue by Shrapnel21** [LIJI32/SameBoy#322]
First of all, thanks for writing SameBoy: it's awesome. =)
With that said, I just bought Super JetPak DX from Asobi Tech and received the complimentary ROM, but it behaves weirdly on SameBoy. It seems the game accelerates and slows down every now and then and thus the game's speed is very inconsistent.
Did anybody have a chance to test the same ROM on SameBoy?

**Comment by LIJI32** [comment]
Appears to not be a bug, might be some CPU-revision dependent issue:
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/2345928/103809717-99115880-5062-11eb-9e2d-5ed58493cffa.png">

**Comment by Shrapnel21** [comment]
Oh, I see. Didn't know about that, guess they used a lot of 'programming tricks' and so the game doesn't work as it should on every single piece of hardware. Oh well, problem solved. =D
