### ISSUE TITLE
[Feature Request] Support .gbc cartridge files

### ISSUE THREAD

**Issue by wjmelements** [LIJI32/SameBoy#338]
Coming from VBAM I'm not sure what cartridge format is expected. On VBAM the dropdown indicated which type I was trying to open ("Open GB", "Open "GBC"), but on SameBoy it's unclear; it only says "Open". None of the files in my collection seem to match what SameBoy is looking for though.

I would appreciate .gbc support and some indication of what file format it is expecting.

**Comment by wjmelements** [comment]
Included screenshot of greyed-out .gbc on MacOS Big Sur.
<img width="840" alt="Screen Shot 2021-01-31 at 2 27 12 PM" src="https://user-images.githubusercontent.com/799573/106399929-6abc3a00-63d0-11eb-86c0-4f5ad9df432b.png">

**Comment by LIJI32** [comment]
You're encountering [this macOS bug](https://github.com/LIJI32/SameBoy/issues/263) that is beyond my control. The linked issue contains workaround instructions.

**Comment by wjmelements** [comment]
Thanks. Removing vbam and running that command fixed it.

**Comment by wjmelements** [comment]
I suspect there is also a way for the Open menu to target `.gbc` specifically, and it might not fail in that case even despite associations.
