### ISSUE TITLE
Taito Variety Pack (Japan) does not load correctly.

### ISSUE THREAD

**Issue by MapleStoryPSN** [LIJI32/SameBoy#339]
When launching the Game Boy title Taito Variety Pack, the game loads directly into Sagaia instead of launching to the Taito Variety Pack title screen and menu to select the game you'd like to play (Bubble Bobble, Elevator Action, Taito Chase HQ, and Sagaia).

mgba can load the game correctly.

**Comment by LIJI32** [comment]
The MBC this ROM uses is not supported yet, it is planned for a later version (The standalone versions of SameBoy should warn you about it)

**Comment by sczther** [comment]
Fixed in the current master
