### ISSUE TITLE
On Virustotal it triggers one Antivirus as "Trojan.Malware.106557651.susgen"

### ISSUE THREAD

**Issue by Minecodes** [LIJI32/SameBoy#342]
Hello, i want to install it, but Virustotal has a trigger on Maxsecurity as "Trojan.Malware.106557651.susgen
" and now i want to know, if it's a false positive trigger.

**Comment by LIJI32** [comment]
VirusTotal is full of F-class obscure anti-virus products that should never be used and definitely should not be trusted. This is obviously a false-positive.

**Comment by Minecodes** [comment]
Thank you 👍
