### ISSUE TITLE
Inaccurate DMG zombie mode

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#344]
When testing on my DMG A/B/C, the attached ROM plays back a pulse signal that quickly alternates between amplitudes 0 and 1.

When tested on Sameboy 0.13.6b, the signal occasionally transforms into a constant tone.

[player.gb.gz](https://github.com/LIJI32/SameBoy/files/5963989/player.gb.gz)

**Comment by jkotlinski** [comment]
On further investigation. Is it a bug here? Zombie writes incorrectly re-enable hardware envelope?

https://github.com/LIJI32/SameBoy/blob/8ad08c1b35a6f03462803b2a6c12eae716b02274/Core/apu.c#L325

**Comment by LIJI32** [comment]
There indeed seem to be bugs in my zombie mode emulation, but if I understand what you mean, this isn't one of them. changing the lower 3 bits of NRx2 can indeed enable the volume envelope even after the sound started (I just verified it to be sure)

**Comment by jkotlinski** [comment]
OK.. I have no idea what might be wrong, but is this perhaps a hint?

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/544715ddaa2852a0aed8d4558154953d39bc3687/src/apu/Gb_Oscs.cpp#L214
