### ISSUE TITLE
make CAN_INSTALL override

### ISSUE THREAD

**Issue by NieDzejkob** [LIJI32/SameBoy#353]
On NixOS, the build environment doesn't contain `xdg-open`, even though it conforms to FreeDesktop. Thus, to use `make install`, one needs to set `DATA_DIR` and `CAN_INSTALL` manually. It would be nice if the detection could be overridden with something like `FREEDESKTOP=true`.

**Comment by NieDzejkob** [comment]
I don't see how that helps. One still needs to set up `DATA_DIR` manually.

**Comment by NieDzejkob** [comment]
To clarify, I'm not saying `FREEDESKTOP` is some standardized variable.

**Comment by LIJI32** [comment]
Oh that's true, let me Fix It Better™

**Comment by LIJI32** [comment]
Yeah I realize it's not, but I find it a better variable name.
