### ISSUE TITLE
install target puts binary away from assets

### ISSUE THREAD

**Issue by Jan200101** [LIJI32/SameBoy#354]
`make install` puts the sameboy binary into the expected binary directory but the assets required for sameboy to work are put in $PREFIX/share/sameboy causing sameboy to crash when trying to run

solution: install sameboy executable to $PREFIX/share/sameboy and symlink it to $PREFIX/bin

**Comment by LIJI32** [comment]
This is intentional and handled but shouldn't crash. Could you add `printf("background: %s\n", resource_path("background.bmp"));` to the start of `main` and see what it prints out?

**Comment by Jan200101** [comment]
nevermind, user error
DATA_DIR was only set during installation

incase handling all possible crashes is desired the crash happens in run_gui() at SDL/gui.c+1125
the background pointer points to NULL and the dereference on line 1125 casues a SIGSEGV
