### ISSUE TITLE
Permission issue when launching on Big Sur 11.2.1

### ISSUE THREAD

**Issue by livid** [LIJI32/SameBoy#360]
OS: macOS 11.2.1
CPU: M1

I got the following dialog when launching:

<img width="372" alt="Screen Shot 2021-03-05 at 3 21 28 PM" src="https://user-images.githubusercontent.com/11427/110185702-e4788680-7dc7-11eb-813a-22fc9604bab7.png">

**Comment by LIJI32** [comment]
I suspect this is because I used an older toolchain that didn't certificate-less sign the arm64 slice; can you confirm this version works? 
[sameboy_cocoa_v0.14.2.zip](https://github.com/LIJI32/SameBoy/files/6095344/sameboy_cocoa_v0.14.2.zip)

**Comment by LIJI32** [comment]
This seems to solve the issue, redownload from https://sameboy.github.io/posts/release-0.14.2 to fix this.

**Comment by livid** [comment]
Yes, it is working now. Thanks!
