### ISSUE TITLE
[Feature Request - Libretro] Cheat Support

### ISSUE THREAD

**Issue by ds22x** [LIJI32/SameBoy#367]
Right now only the Cacoa port has cheat support, but it would be nice if it could be implemented for the Libretro port as well.

**Comment by LIJI32** [comment]
Cheats are generally implemented by the libretro backend (RetroArch for example) and not by the emulator core, as long as the core provides the required APIs (and SameBoy does). AFAIK SameBoy already supports cheats in RetroArch, so you might  to ask the libretro team if they're not working for you.

**Comment by ds22x** [comment]
Well, they aren't implemented for RetroArch (at least for Windows 10 as far as I can tell), but I'll just open up an issue in the LibRetro fork repository instead then.
