### ISSUE TITLE
Function disassembled as `IO_HDMA1`

### ISSUE THREAD

**Issue by ISSOtm** [LIJI32/SameBoy#37]
I have a function located at `$0051`, called `SwitchRAMBanks` (SameBoy correctly loads and displays its name from the SYM file accompanying my ROM), but the instruction that reached it was displayed as `CALL IO_HDMA1 ; =$0051`, whereas I expected my function's name instead.

**Comment by LIJI32** [comment]
Can you attach the sym file?

**Comment by ISSOtm** [comment]
[symfile.zip](https://github.com/LIJI32/SameBoy/files/1769087/symfile.zip)

**Comment by LIJI32** [comment]
[I'm a dummy](https://github.com/LIJI32/SameBoy/blob/master/Core/z80_disassembler.c#L506)
