### ISSUE TITLE
Donkey Kong Land in SGB mode

### ISSUE THREAD

**Issue by Gregoras** [LIJI32/SameBoy#372]
I found issue in DKL on title screen when is played in SGB or SGB2 mode. All characters are brown, when in SGB mode should have some more colors.

**Comment by LIJI32** [comment]
Can you provide a screenshot of how it's supposed to look? It looks identical when comparing SameBoy's HLE SGB emulation to bsnes+SameBoy's LLE SGB emulation.

**Comment by Gregoras** [comment]
It's not screenshot, because I have no idea how to make screenshot from old SNES hardware, but it should look like that: [https://tcrf.net/images/6/62/DKLTitle.png](url)

In my case, on newest SameBoy (Windows version) it look that: [https://www.dropbox.com/s/dub4j0uevvxlbwg/Bez%C2%A0tytu%C5%82u.png?dl=0](url)
