### ISSUE TITLE
Inaccurate noise channel emulation

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#375]
When played back on real DMG, the attached ROM has a nice and regular rhythm.

When played back on Sameboy v0.14 in DMG mode, many of the sounds are completely lost.

[player.gb.gz](https://github.com/LIJI32/SameBoy/files/6320851/player.gb.gz)

**Comment by jkotlinski** [comment]
This appears fixed in 0.14.3

**Comment by LIJI32** [comment]
Probably fixed in 0.14.2 and not 0.14.3, 0.14.3 did not contain any audio changes.
