### ISSUE TITLE
[GBS] Support GBS with load address < 0x400

### ISSUE THREAD

**Issue by jprjr** [LIJI32/SameBoy#376]
The GBS spec lists the valid range of load addresses as 0x400 - 0x7fff, but in my archive, many GBS files use a lower load address.

I wrote a quick utility to go through and find unique load addresses, here's what I've found - this table lists the out-of-spec load address, along with the number of GBS files using that load address. Let me know if you need any example GBS files and how to get them to you (I assume you don't want them posted directly to github).

| Load Address | Number of GBS |
|---------------|----------------|
| 0x0000 | 7 |
| 0x0070 | 198 |
| 0x0170 | 1 |
| 0x01c0 | 1 |
| 0x01f0 | 1 |
| 0x01ff | 1 |
| 0x0200 | 3 |
| 0x0260 | 1 |
| 0x0270 | 1 |
| 0x02e0 | 1 |
| 0x02ee | 1 |
| 0x02f0 | 1 |
| 0x0360 | 1 |
| 0x0370 | 1 |
| 0x03c0 | 2 |

**Comment by LIJI32** [comment]
I updated the loader to allow any loading address greater than 0x6E, which is the bare minimum required for SameBoy's generated player ROM. This should allow all ROMs other than the first 7. Those with loading address 0x0000 can't possibly work with SameBoy as they require inherently less accurate emulation to work.

**Comment by jprjr** [comment]
Awesome! Thank you so much

**Comment by LIJI32** [comment]
Can you list the 0 load address ones? I might have a workaround for these.

**Comment by jprjr** [comment]
Sure thing:

* Jinsei Game Densetsu
* Jungle Wars
* NFL Football
* Uchuu Senkan Yamato
* Ultraman Club - Teki Kaijuu wo Hakken Seyo
* Vattle Giuce
* Yomihon Yumegoyomi - Tenjin Kaisen 2

**Comment by LIJI32** [comment]
The workaround worked, the latest commit adds support for GBS files with a loading address at 0 (So the valid values of the loading address are 0 and 0x6E to 0x7FFF)

**Comment by jprjr** [comment]
Awesome!! This is great
