### ISSUE TITLE
Graphical corruption with Intel i5-10300H's integrated GPU (Intel UHD Graphics)

### ISSUE THREAD

**Issue by TopHatHipster** [LIJI32/SameBoy#383]
When testing SameBoy 0.14.3 on my new hardware, I've noticed green and purple stripes corrupting the graphics of the emulator.

![sameboy_XJDV9ExrTB](https://user-images.githubusercontent.com/43381730/116786029-04ad8480-aa9d-11eb-92b6-8b65862fca3e.png)

When using my dedicated, NVIDIA RTX2060 Mobile, GPU, the emulator's graphics are fine. I have not encountered graphical issues with other programs yet, with my Intel iGPU.

I've regression tested it up to version 0.12 and it still displays the same issue.

Using the following hardware:

CPU: i5-10300H @ 2.50GHz
GPU: Intel UHD Graphics (integrated)/NVIDIA RTX 2060 Mobile
Memory: 16GB
Intel driver version: 27.20.100.8280 (most recent)
Intel Shader version: 5.1
DirectX 12
Vulkan 1.2.137

**Comment by LIJI32** [comment]
Fixed by updating drivers.
