### ISSUE TITLE
command line?

### ISSUE THREAD

**Issue by placeboyue** [LIJI32/SameBoy#384]
i wanna use this with a frontend but im not finding a way to run the games in fullscreen. Is there a command line guide? i''m not finding it anywhere.

other features i'd like are disabling the boot screen (i'd leave it, but the option would be nice) AND a very simple but very important QOA... being able to go UP from the top option in the menu and appear at the bottom. It's a total hazzle to go all the way to "back" to return to the games. Also sometimes the game reset when leaving the menu.

this emulator is so so close to being everything i need, i hope it keeps improving. cheers

**Comment by LIJI32** [comment]
It already exists – `--fullscreen`.

**Comment by LIJI32** [comment]
I made the SDL frontend display the usage string if an invalid option (including `-h` or `--help`) is used to make this option more visible.
