### ISSUE TITLE
"Cartridge type e2 is not yet supported" Ham-Ham Heartbreak

### ISSUE THREAD

**Issue by Stevosss** [LIJI32/SameBoy#387]
More of a missing feature than a bug but- no rush! I was looking forward to playing Ham-Ham Heartbreak with the uh "fuzzy" audio settings to make it more *genuine*, and just incase this IS a bug, I tested it on "virtual boy advance" and 2 diff roms, both worked fine, Windows 10 x64

**Comment by LIJI32** [comment]
Ham-Ham Heartbreak is a Game Boy Advance game, SameBoy is an emulator for Game Boy, Super Game Boy and Game Boy Color games. Emulation of the Game Boy Advance in SameBoy is for Game Boy Color games running on a GBA.
