### ISSUE TITLE
Can't Link with Same Game in RetroArch Core

### ISSUE THREAD

**Issue by TradeDraft** [LIJI32/SameBoy#40]
I tried something last night.

That IF you load the Same Game Up then it will not work at all. Only Works when you have 2 DIfferent Games in the 2 Gameboys.

Video I made Here:

https://www.youtube.com/watch?v=6nspM67aQzU

I guess Using the Same Game when Trading it kind of Stupid but IF you playing 2 Player with the game you can’t.

**Comment by fr500** [comment]
FWIW I tried the same:

https://www.youtube.com/watch?v=ZpCH9xYN1co

And it worked just fine...

**Comment by TradeDraft** [comment]
I tried Pokemon Gold Too but did not Work:

https://www.youtube.com/watch?v=nim9c0Z8ztc&feature=youtu.be

Save Here:

https://www.sendspace.com/file/k5u75h

**Comment by TradeDraft** [comment]
Okay I tried with getting the Latest .info.

No only the 1st Gameboy has a Save File while the 2nd Gameboy has no Save.

How do I fix that?

Like Here when I did it:

https://www.youtube.com/watch?v=e1H9Mmohc8w&feature=youtu.be

**Comment by TradeDraft** [comment]
So Can't Deleate the 1 above I relised I did not use the GameLink Sorry about that

**Comment by fr500** [comment]
Just thought worth mentioning, I can't reproduce these issues.

**Comment by fr500** [comment]
@LIJI32 close this, it was a user issue

**Comment by TradeDraft** [comment]
Yeah. Found out it was because I used same Gamepad for Both Gameboys
