### ISSUE TITLE
Error in timer glitch code

### ISSUE THREAD

**Issue by MrMetric** [LIJI32/SameBoy#409]
`GB_emulate_timer_glitch` in Core/timing.c says:
```c
/* And now either the timer must be disabled, or the new bit used for overflow testing be 0. */
if (!(new_tac & 4) || gb->div_counter & new_clocks) {
```

The comment and the code do not match. I made a test ROM to check what happens when switching the trigger from a 1-bit to a 0-bit with the assumption that it increments `TIMA`. The test passes on my `DMG-CPU A` and my `DMG-CPU B`. SameBoy 0.14.5 (345e51647f2a7ce1ea39f21497f5a6dc75a587c8) fails the test (tested with Nintendo's `dmg_boot.bin`).

I found that changing line 437 to match the comment makes it pass and does not affect any Mooneye GB test results or any Blargg test results:
```c
if (!(new_tac & 4) || !(gb->div_counter & new_clocks)) {
```

For your verification, here is [the test ROM](https://stuff.thingies.site/gbtest/timer_00_to_01_trigger.gb) and [the source](https://stuff.thingies.site/gbtest/timer_00_to_01_trigger.s) (requires Mooneye GB common test code).

Side note: SameBoy also fails Blargg's dmg_sound test despite the README saying all pass. My test results are available in more detail [in this spreadsheet](https://docs.google.com/spreadsheets/d/1BemLslEU6mnQcMWKe7-WXUOV19HjmJFxPleoad_k6Hg/edit).

**Comment by LIJI32** [comment]
Looks like you're right, this is a mistake I made and the condition should be negated. As for the spreadsheet, it looks like a regression (0.14.5 passes) and for some reason the GitHub action failed to catch it. :|
