### ISSUE TITLE
 SameBoy Real Clock not Working Libretro Cores

### ISSUE THREAD

**Issue by TradeDraft** [LIJI32/SameBoy#41]
When I re-set the Time to the Proper Time it works but when I exit out and Comes Back the Time is still the Same as it was when I exited and not the Real Time on the Computer. I am using Windows 10 Made a Video showing what I mean:

https://www.youtube.com/watch?v=zJ_FqZ8G3WI

**Comment by LIJI32** [comment]
Seems like the libretro core isn't saving the RTC offset correctly. I'll have a look this weekend.

**Comment by 777sha** [comment]
I'd want this fixed too :p

**Comment by creambits** [comment]
libretro.c
```
size = sizeof (gameboy[0].rtc_real);

==>

size = sizeof (gameboy[0].rtc_real) + sizeof (gameboy[0].rtc_latched) + sizeof (gameboy[0].last_rtc_second);
```

Kludgy but demo test works with Pokemon Silver. We need to save last_rtc_second for time to tick forwards when offline. If you go backwards in timestamp, then you'll have to reset the game rtc manually in retro_run or retro_reset or retro_load_game.
```
gb->last_rtc_second = time(NULL);
gb->rtc_real.high |= 0x80; /* This gives the game a hint that the clock should be reset. */
```

**Comment by LIJI32** [comment]
I'm going to change a few things in how SameBoy handles the RTC in 0.11.2, I'll fix this soon after that.

**Comment by AnotherLife** [comment]
Is RTC working in the libretro core? I am using a build from around January. In Pokemon Crystal 1.1 no time passes.

Is it working in newer builds? (In Retroarch?)
