### ISSUE TITLE
Feature request: exit menu with B button

### ISSUE THREAD

**Issue by clavinet** [LIJI32/SameBoy#419]
Navigating menus could be much faster by pressing the 'B' button to exit instead of having to go down and selecting 'Back'.

**Comment by Buggem** [comment]
> Navigating menus could be much faster by pressing the 'B' button to exit instead of having to go down and selecting 'Back'.

Note that you can use the Escape key on Windows or Linux (SDL2 builds)

**Comment by LIJI32** [comment]
This has been already added in 0.15, closing
