### ISSUE TITLE
libretro rewind feature randomly crashes and sometimes causes graphical glitches

### ISSUE THREAD

**Issue by prataczak** [LIJI32/SameBoy#42]
What the title says. Tested with 'Batman' for GB.

Here's a screenshot of the game crashing while trying to rewind:

![20180309045927](https://user-images.githubusercontent.com/12243933/37201869-e43a348a-2356-11e8-8316-fae2b4892bdd.png)

Here's a screenshot of graphical glitches after stopping a rewind:
![20180309050251](https://user-images.githubusercontent.com/12243933/37201963-3660bc34-2357-11e8-831f-e502f5e40093.png)

And here's a screenshot of the game crashing after subsequently trying to exit the game after stopping a rewind (this happens a lot too). I suspect this has something to do with the fact that I have RetroArch set to save a state on exit.

![20180309050257](https://user-images.githubusercontent.com/12243933/37202022-602fa6ec-2357-11e8-9f98-b8c7c06346f0.png)

**Comment by fr500** [comment]
Can you get a stacktrace?

**Comment by prataczak** [comment]
Is stacktrace the same thing as log? (pardon my ignorance :) )

**Comment by prataczak** [comment]
I'll assume the answer to my question is yes, please give me instructions on how to proceed otherwise.

Log 1 - RetroArch crashes when 'escape' is pressed to exit emulator, after rewinding for a couple of seconds, and waiting a couple more. https://pastebin.com/x1D2Xw9j

Log 2 - RetroArch crashes as soon as the rewind hotkey is released.  https://pastebin.com/XRR5mS3Q

Log 3 - RetroArch displays glitched graphics after release of rewind key, then crashes when 'escape' key is pressed.  https://pastebin.com/E2HDqPpA

Again, I do have 'Auto Save State' turned on. I suspect that has something to do with the crash on exit.

**Comment by prataczak** [comment]
More details that may be helpful - the ROM's crc is 6C41D3CD, and is called Batman - The Video Game (World).gb. It is loaded from a zipped archive.

I am using Windows 10 with the latest updates.

**Comment by LIJI32** [comment]
I'll try to reproduce it on my Mac, probably some silly memory management issue.

**Comment by LIJI32** [comment]
...But rewinding doesn't seem to work for me at all with RetroArch, holding the rewind key seems to do nothing :S

**Comment by LIJI32** [comment]
Managed to reproduce a memory corruption on the macOS build after using rewind, should be easy now.

**Comment by LIJI32** [comment]
Opened a relevant RetroArch issue (libretro/RetroArch#6382)

**Comment by fr500** [comment]
Thanks for looking into it!
