### ISSUE TITLE
[Request] Analog stick controls for Kirby Tilt 'n' Tumble

### ISSUE THREAD

**Issue by wickjames086** [LIJI32/SameBoy#423]

**Comment by eVenent** [comment]
Analog stick is ok, but I would like to request Cemu hook support (Cemu, Dolphin, Citra, etc.) on PC. I think it is easier than adding support for every controller which supports gyro. Cemu hook is already integrated in emus and uses the motion sensors in controllers like Steam Controller, Dualshock 4, DualSense, Switch Pro Controller, Joy-Cons to play motion sensor games (like Kirby Tilt 'n' Tumble). What is good with this implementation is that 3rd party programs (like eg. reWASD which recently added cemu hook for every controller with gyro) are responsible for sending motion signal in proper way.

Main website: https://cemuhook.sshnuke.net/
UDP Pad motion data provider info: https://cemuhook.sshnuke.net/padudpserver.html
