### ISSUE TITLE
Distorted audio in SameBoy 0.14.7 (macOS), but Windows is fine

### ISSUE THREAD

**Issue by sttng** [LIJI32/SameBoy#438]
I have a music demo build with GBStudio (using a .mod file). The music contains some panning from left to right:

The audio output on macOS SameBoy 0.14.7 is distorted with some "zapping" sounds in panning.
It works on Windows SameBoy 0.14.7 and also on real hardware DMG.

Test here (if you are on macOS, please lower volume first).

https://github.com/sttng/gb-stuff/blob/main/GB_Bloody_Tears.gb

**Comment by LIJI32** [comment]
Hi, can you ensure you're indeed using the same high-pass-filter setting and the same emulated model model across these tests? Audio being distorted exclusively in the macOS version sounds quite unlikely.

**Comment by sttng** [comment]
Thanks a lot for the feedback! Indeed it was the High-pass filter setting. On macOS it was set to "Preserve Waveform", and on Windows it was set to "Accurate".

Many thanks.

Can be closed - unless, you want to keep it for bug-reference to work on the High-pass filter setting "Preserve Waveform".

**Comment by LIJI32** [comment]
The latest version indeed had a major issue in this setting, which was fixed in master a few days ago.
