### ISSUE TITLE
Checksums for release files

### ISSUE THREAD

**Issue by redactedscribe** [LIJI32/SameBoy#441]
Would it be possible to provide a checksums file with each new SameBoy release?

For example, a "Checksums_SHA-265" file formatted as:
```
0cc8acb65beac9a53d56d28aa2f57a78c364b28ca4f84e74fc03b4f800ff93bb  sameboy_cocoa_v0.14.7.zip
d49159fd1ea612bc7e8008028e599b5b01821a080628b548b21b0d276577f349  sameboy_winsdl_v0.14.7.zip
```

This would allow software like the Windows package manager [Scoop](https://github.com/ScoopInstaller/Scoop) to avoid having to download the archive to calculate its checksum locally and instead rely upon the value in an online "Checksums_SHA-265" file. In addition, checksums could be published on the GitHub site too, but in Scoop's case, a checksums file is sufficient.

[Release example](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.03.08.1).

Thanks!

**Comment by LIJI32** [comment]
I added this to my release build script, should be available for the next release.
