### ISSUE TITLE
PCM playback in GHX tech demo not working

### ISSUE THREAD

**Issue by bryc** [LIJI32/SameBoy#46]
This [GHX tech demo](https://github.com/LIJI32/SameBoy/files/1823027/ghxsmp.zip) doesn't appear to play the PCM samples properly. Works fine in Gambatte and BGB.

**Comment by LIJI32** [comment]
Seems to play fine for me in both 0.10.1 and master. Which version are you using?

**Comment by LIJI32** [comment]
I see what you're talking about. The buzz you hear while PCM samples are playing is digitally accurate (not emulating it entirely, like BGB and Gambatte, is wrong). However, the *volume* of this buzzing is a depends non deterministic analog quirk of the Game Boy audio system, and is not very accurately emulated in `master`, and not emulated at all in the stable versions. This is the same issue as Cannon Fodder's audio buzz.

Running this demo on real hardware will still result in a buzz.

**Comment by bryc** [comment]
I'm using 0.10.1-winsdl under Win7. Wouldn't know how to compile master. [This (audio clip)](https://instaud.io/_/1Vi2.ogg) is what I meant though. 

SameBoy/VBA-M/mGBA exhibit a loud tone playing alongside the samples (0:00-0:10 in the clip), while BGB/Gambatte/nezplug++ does not (0:10-0:20 in the clip). 

Is that loud tone in the first clip what you mean by 'buzz'? Does legit hardware really sound that bad? :disappointed: 


****

Also I have a slightly related bug report to merge here (dunno about you but I hate huge issue lists). 

When pausing SameBoy when sound is playing, there is 'inaudible' high-frequency sound coming through. 

I see this but I hear nothing:

![image](https://user-images.githubusercontent.com/1408749/37570866-dfd11ce8-2acb-11e8-8631-7f0d3d339536.png)

I recorded it, and looking at the audio spectrum, each time the audio 'pops' (red spike in the spectrum), much like the 'pop' at the initial start of emulation. Then there is an incremental frequency sweep at a very low volume, and it screws with the Windows sound mixer and interferes with other application's sound.

![image](https://user-images.githubusercontent.com/1408749/37570682-2fc2eb44-2ac9-11e8-97ab-969ec81a34c6.png)
