### ISSUE TITLE
Issue with pokemon crystal

### ISSUE THREAD

**Issue by 777sha** [LIJI32/SameBoy#47]
![pokemon - crystal version usa europe rev a -180319-183339](https://user-images.githubusercontent.com/18407984/37612171-b860fe88-2ba4-11e8-83f4-b861a394033a.png)

Using windows 10 x64, opengl driver
Using latest version of sameboy, the same happens with no shaders.

Rom was pokemon crystal europe rev A  no intro

Some other users have reported the same issue as well for pokemon crystal 1.1

**Comment by LIJI32** [comment]
Oh god that's a nasty regression
