### ISSUE TITLE
[Request] Gamepad work outside window.

### ISSUE THREAD

**Issue by ZxCFss** [LIJI32/SameBoy#472]
For multiple screen, gamepad work outside window is really a nice feature to have.

**Comment by LIJI32** [comment]
Cocoa or SDL?

**Comment by ZxCFss** [comment]
Sorry i'm just an end user I've never heard of Cocoa, as for SDL, that usually what other emulator has as an option.

**Comment by LIJI32** [comment]
I mean, the macOS version or SDL/Windows/Linux version?

**Comment by ZxCFss** [comment]
SDL it is then, I'm window user.

**Comment by LIJI32** [comment]
Ah, I'll have to see if the SDL supports this feature. If so, I can add it to the next release.

**Comment by ZxCFss** [comment]
Awesome ! Thank you very much !
And since I don't see any place where I can discuss other stuff with you (Discord, forum, etc)
Hope you don't mind me asking here.

From what i google and found, GBC Revision refer to different model of Physical GBC with different CPU, but now that there's option to choose from, which one should i choose? (Not sure if i did change anything by mistake, but mine is on CGB E)

Also another request (though not as important as the Topic request). Could you also add option to set path for save files / save state instead of auto to where the ROM is located?

Thanks again !

**Comment by LIJI32** [comment]
CGB-E is the recommended CGB revision to use. As for save paths, this is problematic as associating a ROM with its save path is non-trivial this way; most solutions don't cover all use cases, and it's generally confusing to end users. For example, I associate based on the ROM title, ROM hacks of the same game will get the same saves. If I use file names or full paths, renaming or moving a ROM will make the saves unavailable until moved back. And finally, in every solution, having multiple instances of the same game (i.e. multiple save files) becomes non-trivial and confusing to the end user.
