### ISSUE TITLE
Crash on fastforward (SDL Windows port)

### ISSUE THREAD

**Issue by JukePlz** [LIJI32/SameBoy#473]
Holding the fastforward key for more than 1 second crashes, on any game, using the SDL Windows port.

This didn't happen in 14.7, so the bug was introduced in 15.0, and is also present in the current release 15.1

Seems to be related to the default audio driver change, as forcing the driver to SDL the fastforward function doesn't crash anymore.

**Comment by LIJI32** [comment]
Which audio driver are you using when it happens (XAudio2 or XAudio2_7)? Which version of Windows?

**Comment by JukePlz** [comment]
Windows 7. The driver shows "XAudio2_7", even when selecting the XAudio2 option, so I think either of them are selecting the same driver, not sure if this is intended. Both of the XAudio options crash in fast forward.
