### ISSUE TITLE
Request: Configure Hotkeys

### ISSUE THREAD

**Issue by TomTurbine** [LIJI32/SameBoy#474]
Trying to set something up where it runs from a controller. I see hotkeys under the help section but no way to configure any hotkeys.

Main 2 settings I was looking for was to auto-start in full screen and a hotkey to exit I could configure using a PS5 controller.

Besides that, just a full portable setup where it doesn't use my Roaming folder to store preferences and just saved it in the emulators main directory.

I know I can set it up under Retroarch as a core but like keeping the systems and their save files separate, so trying to go standalone when I can.

**Comment by LIJI32** [comment]
I'll add these for the new minor release. Auto-start in full screen is already available by using the "--fullscreen" command line argument (On Windows you can use a shortcut for that). Portable mode is also available – if you move your prefs file to be by the executable, SameBoy will switch to portable mode.

**Comment by TomTurbine** [comment]
Thank you very much. Didn't know about the portable part and couldn't seem to find a link to the command line arguments.

So the main thing I was missing was the exit hotkey.

Much appreciated.

**Comment by TomTurbine** [comment]
Off-topic

Sameboy doesn't support 7-zip does it?
