### ISSUE TITLE
"The save path for this rom is not writable..." even when the path is writable and game can save.

### ISSUE THREAD

**Issue by JukePlz** [LIJI32/SameBoy#478]
This warning is showing up even when the game can correctly save. This only happens when there is no save file in the rom directory. If a save file is already present SameBoy won't output the warning message.

SDL frontend. Windows 7.

**Comment by LIJI32** [comment]
This bug will be fixed in a quick release coming tomorrow.

**Comment by JukePlz** [comment]
Resolved: fixed.
