### ISSUE TITLE
Audio regression: Noisy pulse channel vibrato

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#483]
Pulse channel vibratos sound like a Geiger counter. The problem is worse for higher octaves. It does not sound like that on real hardware. The problem appeared in Sameboy 0.12.3.

**Comment by jkotlinski** [comment]
This ROM should demonstrate the issue. [player.gb.gz](https://github.com/LIJI32/SameBoy/files/9274202/player.gb.gz)

**Comment by jkotlinski** [comment]
Here is a .wav file that illustrates the difference (DMG vs Sameboy). Sameboy sounds broken.

[dmg_sameboy_pu_v00.zip](https://github.com/LIJI32/SameBoy/files/9313778/dmg_sameboy_pu_v00.zip)

**Comment by LIJI32** [comment]
Bisecting this issue and figuring out it was a 0.12.3 regression helped a lot, thanks!

**Comment by jkotlinski** [comment]
Thank you for the fix!!!
