### ISSUE TITLE
resources.rc error building on Windows 10

### ISSUE THREAD

**Issue by jwalway** [LIJI32/SameBoy#485]
Hello I'm using mingw (msys) to build on Windows 10.     The build is running into problems generating the resources.rc file.   

I know there is a chcp 65001 command.  This command doesn't seem to work from the Makefile, either in Windows CMD window or Bash, so I run it manually successfully before running make.  Apparently this is for utf-8.    However, even when I run it manually I get the same problem.

Here is the error. I just included the last few lines due to redundancy:
```
Windows/resources.rc:24:81: warning: null character(s) ignored
   24 |  I D I _ I C O N 1   I C O N   D I S C A R D A B L E   " S a m e B o y . i c o " 
      |                                                                                 ^
Windows/resources.rc:25:1: warning: null character(s) ignored
   25 |  
      | ^
C:\MinGW\bin\windres.exe: Windows/resources.rc:1: syntax error
make: *** [build/obj/Windows/resources.o] Error 1
```

Maybe it wants utf-16?  I couldn't find a way to activate that, as the "chcp 1200" command returns an invalid code error.

Thanks for any help!

...John

**Comment by LIJI32** [comment]
IIRC the `chcp` commands are there to fix build issues when compiling SameBoy on Windows machines that have their locale set to Japanese, and have nothing to do with this issue. As far I can see, `windres` does not support *any* Unicode encoding, while Microsoft's `rc` requires UTF-16 for Unicode. This is a long standing issue with `windres` that MinGW developers don't seem willing to fix. MinGW is neither the recommended nor standard way to build SameBoy for Windows, [the recommended way](https://github.com/LIJI32/SameBoy/blob/master/build-faq.md) is using Clang for compilation, GNUWin32's Unix utilities for the build system, and Visual Studio's headers and Windows-specific tools. With MinGW lacking trivial functionality such as Unicode support for resources, I believe the only reasonable solution is to drop support for resources when compiling using MinGW.

**Comment by jwalway** [comment]
> 

Thanks for the reply.   I was able to fix part of the problem by saving the file as UTF-8, but then another syntax error popped up for the same resource file.  

I was looking at GNUWin32, and I wasn't sure what to download.  They have a ton of things to download.  http://gnuwin32.sourceforge.net/packages.html

I'll see if I can change over to clang with GNUWin32.

**Comment by jwalway** [comment]
Apparently I am using clang, it's just that I'm using mingw's make and tools.

**Comment by LIJI32** [comment]
You download the [full GNUWin32 installer](https://sourceforge.net/projects/getgnuwin32/files/). Alternatively, you can keep using MSYS and drop `$(OBJ)/Windows/resources.o` from line 393 in the Makefile, which will disable resource compilation.

**Comment by jwalway** [comment]
> You download the [full GNUWin32 installer](https://sourceforge.net/projects/getgnuwin32/files/). Alternatively, you can keep using MSYS and drop `$(OBJ)/Windows/resources.o` from line 393 in the Makefile, which will disable resource compilation.

Thanks a million!   I installed GNUWin32 with that installer and got it compiled!  :-)

Regards,
...John

**Comment by jwalway** [comment]
Btw, one small issue I had that someone else might run into. I used Microsoft's vcpkg to install SDL2.    The compiler couldn't find the SDL2main.lib library.    Apparently vcpkg stores that library in two subdirectories off of the directory where SDL2.lib is.   I don't know if the libraries are identical, but I copied one and put it in the same directory with SDL2.lib and that fixed the problem.
