### ISSUE TITLE
SGB1 Mole Mania -- wrong music speed

### ISSUE THREAD

**Issue by radimerry** [LIJI32/SameBoy#493]
Hi, Mole Mania when run on an SGB1 is supposed to sound exactly like the DMG mode (developers account for the faster SGB clock and adjust the music tempo). On SameBoy, SGB1 sounds maybe 13% slower and pitch is lower because the clock speed is not running faster like in reality.

**Comment by LIJI32** [comment]
Hi, are you sure your SGB model is not set to SGB2, where this is the expected behavior?

**Comment by LIJI32** [comment]
This is actually a bug in the libretro core. Seems like switching a model/revision does not force the frontend to update the timing information, which causes, for example, SameBoy to send audio and video at NTSC SGB rates while the frontend stretches them to SGB2/DMG/CGB rates. Changing other settings or restarting RetroArch fixes this. I'll commit a proper fix to the core itself.
