### ISSUE TITLE
rgbds-0.6.0 - pb12: BootROMs/pb12.c:90: main: Assertion `outctl != 1' failed.

### ISSUE THREAD

**Issue by orbea** [LIJI32/SameBoy#500]
OS: `Gentoo`
rgbds: `0.6.0` (https://github.com/gbdev/rgbds/releases/tag/v0.6.0)
SameBoy: https://github.com/LIJI32/SameBoy/commit/55507274d6efdf3a511eceabf9c89d7a096702b3

The recent rgbds `v0.6.0` release breaks the SameBoy `pb12.c` build.
```
SameBoy/build/pb12 < build/obj/BootROMs/SameBoyLogo.2bpp > build/obj/BootROMs/SameBoyLogo.pb12
pb12: BootROMs/pb12.c:90: main: Assertion `outctl != 1' failed.
Aborted 
make: *** [Makefile:473: build/obj/BootROMs/SameBoyLogo.pb12] Error 134
```

**Comment by LIJI32** [comment]
This looks strictly related to `pb12` itself and not RGBDS, are you sure it's v0.6.0 that broke it?

**Comment by orbea** [comment]
I think this is an intentional change in rgbds.
I bisected it to commit https://github.com/gbdev/rgbds/commit/d86d24bdc14fb2fc5c1ca9729495e1a26c2d6d08.
Which fixed rgbds issue https://github.com/gbdev/rgbds/issues/1062.
```
d86d24bdc14fb2fc5c1ca9729495e1a26c2d6d08 is the first bad commit
commit d86d24bdc14fb2fc5c1ca9729495e1a26c2d6d08
Author: Rangi <remy.oukaour+rangi42@gmail.com>
Date:   Fri Sep 30 17:13:55 2022 -0400

    Remove legacy support for generating a palette with unused colors
    
    If you need an explicit set of colors, possibly including
    unused ones, use `-c`.
    
    Fixes #1062

 src/gfx/pal_sorting.cpp | 25 -------------------------
 1 file changed, 25 deletions(-)
```

**Comment by orbea** [comment]
Changing the `rgbgfx` command line in the Makefile to `rgbgfx -h -u -o $@ $< -c embedded`works.

There are additionally many deprecated warnings including changing `-h` to `-Z`. I fear it may be impossible to support newer rgbds without breaking older rgbds...

**Comment by Rangi42** [comment]
You could check the value of `rgbgfx -V` and use flags depending on its version.

**Comment by orbea** [comment]
> You could check the value of `rgbgfx -V` and use flags depending on its version.

I thought about that, but checking `>= 0.6.0` with pure make is not straight forward. Or do you have an idea how?

**Comment by carmiker** [comment]
In my view it just makes sense to accept that 0.6.0 and beyond require a different set of command line switches. Anyone building this from source or packaging it up will have to contend with this now, and in the long run it is a non-issue. That being said, I think it makes sense to avoid changing command line switches often.

**Comment by Rangi42** [comment]
If you can assume that `rgbasm` has the same version as `rgbgfx`:
```Makefile
$(OBJ)/%.2bpp: %.png
	-@$(MKDIR) -p $(dir $@)
	@if test "$$(echo 'print __RGBDS_MAJOR__>0||(__RGBDS_MAJOR__==0&&__RGBDS_MINOR__>5)' | rgbasm -)" = '$$0'; then \
		rgbgfx -h -u -o $@ $<; \
	else \
		rgbgfx -Z -u -c embedded -o $@ $<; \
	fi
```
(or put that content in `versioncheck.asm` and do `test "$$(rgbasm versioncheck.asm)" = '$$0';`)

**Comment by LIJI32** [comment]
> In my view it just makes sense to accept that 0.6.0 and beyond require a different set of command line switches and building SameBoy now requires >= 0.6.0. Anyone building this from source or packaging it up will have to contend with this now, and in the long run it is a non-issue. That being said, I think it makes sense to avoid changing command line switches often.

I would generally agree, but considering many users install `rgbds` from a package manager, which are often behind by at least a few weeks, I'd rather avoid that. I like @Rangi42's solution.
