### ISSUE TITLE
Online Link Cable?

### ISSUE THREAD

**Issue by KeeveeKoomoo** [LIJI32/SameBoy#503]
Is there a way for me and my friend to trade and battle pokemon using the SameBoy core? I don't know how to set netplay up to use the subsystem option, whenever my friend tries to join my netplay, it just overwrites his saves with my saves.

**Comment by LIJI32** [comment]
It's better to ask in the RetroArch repo or their Discord, as that logic is part of RA and I'm not very familiar with it.
