### ISSUE TITLE
Rename `internal` define

### ISSUE THREAD

**Issue by tommitytom** [LIJI32/SameBoy#508]
The following define causes a few issues with my build, because it replaces any instance of "internal" in any header that includes it:
`#define internal __attribute__((visibility("internal")))`

Is it possible to name it something a bit more SameBoy specific?

**Comment by LIJI32** [comment]
The `internal` macro is guarded by the `GB_INTERNAL` define, which should only be defined while compiling the Core sources themselves (so the Cocoa and SDL sources, for example, don't have it defined). Are you compiling some other sources with `GB_INTERNAL` defined?

**Comment by tommitytom** [comment]
Oh yep, that got it!  I was defining it for the whole project rather than just before the `gb.h` include.  Thanks for the hep :)
