### ISSUE TITLE
Blargg's 7-timing_effect.gb hangs with a blank screen

### ISSUE THREAD

**Issue by nicolas-siplis** [LIJI32/SameBoy#510]
Not sure if a regression was introduced somewhere along the line or if this has always been the behavior, but thought I should report it.

**Comment by LIJI32** [comment]
Seems like a bug with the ROM, my Game Boy Light behaves the same.

**Comment by FitzRoyX** [comment]
> Seems like a bug with the ROM, my Game Boy Light behaves the same.

I think the gameboy light is an MGB cpu, though. I think it's very possible that it passes on either DMG 0 or DMG A/B/C, but not MGB. Can you test?

**Comment by LIJI32** [comment]
My DMG-B behaves the same as my GBL.

**Comment by northbymidwest** [comment]
I looked into this recently, and it appears the serial output buffer is overflowing, causing corruption that leads to stack frame leaks. I didn't take super-detailed notes while doing this, so I can't recall the specifics (though I do remember the stack pointer being way off in lala land during execution). Yes, the ROM does appear to have a bug.
