### ISSUE TITLE
Windows build -- how to set up GnuWin?

### ISSUE THREAD

**Issue by fishcu** [LIJI32/SameBoy#511]
I'm trying to get the Windows build working. 

The link for GnuWin given in the README will lead to GetGnuWin32 here: https://sourceforge.net/projects/getgnuwin32/files/
However, this package seems quite archaic and trying to execute download.bat and install.bat according to the instructions doesn't work at all anymore due to links inside of these batch scripts being broken. I even tried to run a patched download.bat from some community members, but that one didn't work either.

How can GnuWin be set up correctly?

The link for GnuWin found on Google (https://sourceforge.net/projects/gnuwin32/) will only install sed.exe but none of the other required tools.

Is it possible to use some other toolset, e.g., Cygwin, to compile SameBoy instead?

**Comment by fishcu** [comment]
Addendum: 

I also don't have a vcvars32.bat available. Is this still required with newer versions of Visual Studio? This is the exact version I am using at the moment:
```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.5
```

**Comment by LIJI32** [comment]
CygWin and other build environments for Windows may or may not work, I don't have them installed nor have I ever tested them. Contributors have previously added support for them, but they're not regularly tested nor officially supported. SameBoy only requires GNUWin32 for `make` and other various build utilities, clang is to be installed independently from LLVM's website, so as long as you can have any way to obtain these binaries without breaking Clang/VS headers it should be fine. GNUWin32 should be available from [this link](https://sourceforge.net/projects/getgnuwin32/files/getgnuwin32/).

As for vcvars32, I don't know what changed in VS2022, but that environment seems to be the environment for building 64-bit executables. SameBoy currently builds 32-bit executables on Windows, but that is set to change in 0.16 where 32-bit support on Windows will be dropped and replaced with 64-bit.

**Comment by fishcu** [comment]
The link you posted to get GnuWin32 is the same I posted above. It's impossible to install it from that link for the reasons I explained in the original post.
Could you provide additional explanation on how to set it up? It obviously works for you.

**Comment by LIJI32** [comment]
That's the same package I'm using, looks like something broke with the `download.bat` script, but you can bypass the error by passing running `download.bat -c`, which seems to work for me so far. Let me know if it works for you.

**Comment by fishcu** [comment]
Thank you. Unfortunately, the broken sourceforge links permeate to other parts of the script to.

It now hangs at
`= Downloading and verifying 446 new packages from sourceforge.net...`
with 0% CPU usage, 0% disk usage, and 0 network activity in the task manager.

Inspecting what it's doing, it is trying to download the following link:
http://iweb.dl.sourceforge.net/project/gnuwin32/dvidjk/1.0/dvidjk-1.0-bin.zip
, which does not work from where I am at.
A valid link for this archive would be, for example:
https://deac-fra.dl.sourceforge.net/project/gnuwin32/dvidjk/1.0/dvidjk-1.0-bin.zip

So I have to go into the script, or set the env variable, for `GNUWIN32_MIRROR`. 
This will finally start downloading some files, albeit at a slow pace. Will update when it finishes...!

**Comment by fishcu** [comment]
OK, I got a bit further. Installed gnuwin32. `sed` and some other package failed to download, the rest seemed to work.

Tried to `make` again. Set all the paths according to the readme. Got tons of `make (e=2): The system cannot find the file specified.` errors. Tried to install clang from this website according to your earlier comment: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.2, file `LLVM-15.0.2-win64.exe`.

Finally... success!

Suggestion:
- Host the final gnuwin32 directory somewhere so that others don't have to go through the installation process

**Comment by fishcu** [comment]
BTW, I was able to find vcvars32.bat at:
`C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars32.bat`.

**Comment by daltonclaybrook** [comment]
This thread was incredibly helpful, especially the bit about using a different sourceforge mirror such as "deac-fra." Thank you @fishcu and @LIJI32! I wonder if it would be helpful for others to update the Windows build instructions with some of these tips.
