### ISSUE TITLE
Feature request: Hot swap same ROM file

### ISSUE THREAD

**Issue by KelseyHigham** [LIJI32/SameBoy#512]
I'd like to make a small change to a ROM, and hot swap the new version from the filesystem, to quickly preview new graphics or text. Currently this gives an error:
> ‘rom.gbc’ is already open in another window. Close ‘rom.gbc’ before hot swapping it into this instance.

**Comment by LIJI32** [comment]
Do you mean an actual hot-swap (i.e. replacing the ROM contents without restarting the ROM execution) or just a data reload? To merely reload the file you can just reset the ROM with cmd-R which also reloads the ROM and its symbols.

**Comment by KelseyHigham** [comment]
Actual hot-swap.

**Comment by KelseyHigham** [comment]
Workaround:
- quick save
- reload
- quick load

This issue is still relevant – it would be nice to hot-swap within the same window without getting the error message. 

(It's possible that this is less a feature request, and more a bug in whatever is producing the error.)

**Comment by KelseyHigham** [comment]
hmm, i still get the same error on 0.15.8 Cocoa

**Comment by KelseyHigham** [comment]
1. open rom.gbc
2. File > Hot Swap Cartridge…
3. choose rom.gbc
4. > ‘azle-r1.gbc’ is already open in another window. Close ‘azle-r1.gbc’ before hot swapping it into this instance.

**Comment by LIJI32** [comment]
I fixed the issue that prevented hot-swapping a ROM into itself, but I also added a proper option to reload the ROM directly – Cmd+Shift+R (Or holding Shift in the Emulation menu and choosing "Reload ROM"). Starting in 0.16.0, a debugger command can also achieve the same effect – `reset reload`.
