### ISSUE TITLE
Pokemon Silver "It was already caught!"

### ISSUE THREAD

**Issue by dev01111** [LIJI32/SameBoy#513]
This issue is really annoying my friend (I personally haven't encountered it yet)

It is a SameBoy only issue, my other friend has finished the game with VBA-M and never saw these glitches.

When my friend encounters Pokemon, occasionally he can't catch them. A textbox displays telling us that we can't catch it because it was already caught. There is no trainer though, so it must be bad emulation. I don't know why this happens. I can provide a link to the ROM/the website where I downloaded it but will only send it if you want to see it, since I did it without asking the VBA-M community and it got redacted.

(He was just close to catching an overpowered Pokemon but couldn't because of this bug.)

**Comment by LIJI32** [comment]
This is most likely a buggy ROM hack that assumes various emulation inaccuracies that only exist on VBA and will not work on other emulators or real hardware. In any case, I can't solve ROM hack issues without know what ROM hack it is ("It was already caught!" is not a string you can find in the vanilla game).

**Comment by dev01111** [comment]
@LIJI32 Sorry for taking so long to get back, but this is not a hack. This was informed by my friend, he was probably saying a paraphrased version of the actual text. Anyway, he's been playing for quite a while since he upgraded SameBoy and since then it hasn't happened, so I think this bug may have been resolved (without even knowing about it!) I was personally using an older version of SameBoy by 1 compared to the time by friend was using it. So therefore I think this issue should be closed for now, but I will inform you if the glitch comes back.

**Comment by dev01111** [comment]
Again another update that this is a false case. My friend told me that the glitch said 'Aww! It appeared to be caught!' instead which occurs when your Poke Ball fails to catch it. It told my friend that he was very silly for this and he could just use the rewind feature of sameboy.
