### ISSUE TITLE
Can't use custom .png logos in bootrom

### ISSUE THREAD

**Issue by maij** [LIJI32/SameBoy#515]
Is it possible to replace the Sameboy with another logo? I have tried various 128 x 24 2-bit images, but they all result in logo corruption when I build the project.

I am using the latest rgb* libraries (built from source at the latest release).
Is there a special set of rules to make this work? 

# Examples
## Vertical stripes
1px stripes
![vertical_stripes](https://user-images.githubusercontent.com/7358024/203263193-9cabd483-9a02-41ef-bed0-4d856566fd92.png)
![Screenshot from 2022-11-22 08-23-07](https://user-images.githubusercontent.com/7358024/203263222-817cc6b9-84fa-4563-b637-cb167d2ee01b.png)

2px stripes
![vertical_stripes_2px](https://user-images.githubusercontent.com/7358024/203267350-1281483c-8966-4d6a-b3a5-e5ba0d8efb8e.png)
![Screenshot from 2022-11-22 08-44-32](https://user-images.githubusercontent.com/7358024/203267433-9326db66-7f3d-4199-afcd-5b5d5fc4ba64.png)

## Gameboy text
![Gameboy_logo](https://user-images.githubusercontent.com/7358024/203266371-65ca71e6-8ea0-440c-8d77-bf7c41939927.png)
Fails to compile with following message:
```
rgbgfx  -Z -u -c embedded -o build/obj/BootROMs/SameBoyLogo.2bpp BootROMs/SameBoyLogo.png
cc -std=c99 -Wall -Werror BootROMs/pb12.c -o build/pb12
~/SameBoy/build/pb12 < build/obj/BootROMs/SameBoyLogo.2bpp > build/obj/BootROMs/SameBoyLogo.pb12
pb12: BootROMs/pb12.c:90: main: Assertion `outctl != 1' failed.
Aborted (core dumped)
make: *** [Makefile:474: build/obj/BootROMs/SameBoyLogo.pb12] Error 134
```

**Comment by LIJI32** [comment]
The SameBoy logo is compressed under a scheme that is somewhat hardcoded to the SameBoy logo itself:
1. It requires 3 colors (not 2 and not 4) in a particular palette. Using a different palette can trigger an assertion error like the one you've posted.
2. It assumes at specific amount of unique tiles in a specific layout (There are two duplicate tiles in SameBoy's logo, being shared between E and B)
3. Boot ROM space is extremely tight, logos that are slightly less compressible than the current logo simply won't fit.

**Comment by maij** [comment]
Thanks for the response, may I ask what tools you used to create the SameBoy logo? I have tried toying with my own in GIMP but I haven't made any headway there.

**Comment by LIJI32** [comment]
Any tool that properly supports indexed PNGs should work. I specifically use Adobe Photoshop.

**Comment by maij** [comment]
Thanks, I'll close this issue now. I will play around with different bootrom code.
