### ISSUE TITLE
Joypad Not Detected - Steam Deck

### ISSUE THREAD

**Issue by rawdatafeel** [LIJI32/SameBoy#517]
Hello, 

I installed the Flatpak from Discover on SteamOS (Steam Deck), and added the Flatpak to Steam. But, SameBoy doesn't seem to be able to detect the Steam Deck controls. It gives me `Joypad Not Detected`.  

Apologies for the vague issue, I'd be happy to provide more detail.

**Comment by LIJI32** [comment]
Where are you seeing this error message? This is not a string comes from SameBoy's own code. Could you add a screenshot?

**Comment by rawdatafeel** [comment]
Yes, sorry, it's not an error message, accidentally used "detected" instead of "found".

![image](https://user-images.githubusercontent.com/108900299/205137755-87e66665-b141-478d-853e-5b09dcbd6e88.png)

**Comment by LIJI32** [comment]
This is most likely an issue with the flatpak package. Can you see if the issue persists if you build SameBoy from source or use another, non-sandboxed release of SameBoy? If it does, you might want to contact the maintainer of the flatpak package.

**Comment by rawdatafeel** [comment]
I built it from source and it looks like you're right! Sorry about the mix-up. I'll submit an issue for the flatpak.
