### ISSUE TITLE
gamepad  not detected anymore

### ISSUE THREAD

**Issue by jeep0621** [LIJI32/SameBoy#519]
hello
gamepad are not detected on flatpak sameboy 0.15.5
issue is the same as #517 but not steam deck related
xbox x controller not detected
8bitdo pro2 not detected
thanks

**Comment by LIJI32** [comment]
This is most likely an issue with the flatpak package, as these are controllers known to be supported with SDL. Can you see if the issue persists if you build SameBoy from source or use another, non-sandboxed release of SameBoy? If it does, you might want to contact the maintainer of the flatpak package.

**Comment by jeep0621** [comment]
thanks for your help, i didn t remember that it was  indeed working on the pc i compiled sameboy, and not on the flatpak version that is now fixed.
thanks again
