### ISSUE TITLE
Gekkio's NaughtyEmu (OAM DMA + Halt bus conflict) doesn't pass

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#52]
All the relevant info and link to sources should be here: https://forums.nesdev.com/viewtopic.php?f=20&t=16796

**Comment by LIJI32** [comment]
Basically it means I still have work to do when it comes to OAM DMA, makes sense. It's a good idea to measure its exact timings in several edge cases and more cases of potential bus conflicts while I'm at it.

**Comment by sczther** [comment]
Still doesn't work in the latest release.

**Comment by sczther** [comment]
Seems like it passes in GBC mode but not in DMG mode as of the latest master

**Comment by sczther** [comment]
Now shows a blank screen in both CGB and DMG mode. Probably working as intended!

**Comment by LIJI32** [comment]
If I understand correctly, this ROM is a less-polished version of [mgb_oam_dma_halt_sprites](https://github.com/Gekkio/mooneye-test-suite/blob/main/madness/mgb_oam_dma_halt_sprites.s), which I pass (Although, IIRC, that ROM is revision specific and in some cases even instance specific.) I used this ROM to test my OAM DMA halt behavior, and it should pass in all revisions.
