### ISSUE TITLE
Zombie mode inaccuracy on DMG

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#522]
[test.gb.gz](https://github.com/LIJI32/SameBoy/files/10330407/test.gb.gz)

The attached ROM sounds very different on Sameboy and a real DMG.
(Please note, you need to wait a long time until the ROM produces a sound. Maybe it is possible to shorten the loop for test purposes.)

**Comment by jkotlinski** [comment]
It might be worth to test this ROM on CGB-C or earlier. I suspect the same inaccuracy is present on those revisions.

**Comment by LIJI32** [comment]
I'll currently focus on CGB-C because DMG Zombie Mode is non-deterministic. It looks like my CGB-C and CGB-E both sound the same and match SameBoy in CGB-E mode, but SameBoy in CGB-C is completely broken. I'll have to look into that, thanks!

**Comment by LIJI32** [comment]
It appears that while the test ROM produces an emulation inaccuracy only on CGB-C and older, this inaccuracy also exists in SameBoy's CGB-E emulation. This is a very nice catch!
