### ISSUE TITLE
CBG bootrom AGB switch does not set flags correctly

### ISSUE THREAD

**Issue by maij** [LIJI32/SameBoy#524]
This is a small thing I noticed on [these lines](https://github.com/LIJI32/SameBoy/blob/93aa93e42c708e93b0a51ac2238e9fc2ddf5bb4a/BootROMs/cgb_boot.asm#L892L908).

Just before this switch `and a` is called which sets the flags to z010, and the highlighted code is only run for 1010.  
After this, either `add a, $11` is called (setting the flags to 0000) for AGB or for CGB `ld a, $11`, which does not change the flags (leaving 1010).
[Pandocs](https://gbdev.io/pandocs/Power_Up_Sequence.html#cpu-registers) says the CGB flags should be 1000 when starting the game, rather than 1010. Adding a `cp a, $11` to the CGB path would fix this.

Pandocs also suggests using `inc b` to set the final AGB flags when running in DMG mode but it looks like AGB+DMG mode isn't implemented here.

**Comment by LIJI32** [comment]
Both cases starts with `xor a` which clears the H flag and sets the Z flag; setting the flags to the correct value for the CGB boot ROM, 1000. SameBoy passes the relevant test ROM (boot_regs-cgb from Mooneye's test suite) so this appears correct. 

It is true, however, the B register ends up with a wrong value on Nintendo DMG games on the AGB.

**Comment by LIJI32** [comment]
Fixed in commit 2b6cf0c
