### ISSUE TITLE
Register A not initialised by bootrom before use

### ISSUE THREAD

**Issue by deltabeard** [LIJI32/SameBoy#526]
In the [original DMG bootrom](https://github.com/ISSOtm/gb-bootroms/blob/master/src/dmg.asm) register A is cleared using `xor a`, but in the [SameBoy DMG bootrom](https://github.com/LIJI32/SameBoy/blob/801e61a4e7a3b4d122efbfc417cecaae1d15be49/BootROMs/dmg_boot.asm#L10), register A is used before it is initialised, potentially filling the VRAM with a random value.

I'm not sure if this is an actual issue or not though, because it might be possible that the DMG CPU initialises the A register to 0 before executing the bootrom, hence making the `xor a` instruction redundant. Is that the case?

Thanks.

**Comment by LIJI32** [comment]
Technically the initial value of all CPU registers has been confirmed to be 0 (By skipping the CGB boot ROM on a GBA/GBA SP). That said, it's a good idea to explicitly set A's value.

**Comment by deltabeard** [comment]
The issue was fixed with commit 59ecd4b. Thanks!
