### ISSUE TITLE
libretro Build Error

### ISSUE THREAD

**Issue by Awakened0** [LIJI32/SameBoy#528]
When trying to build the libretro target for Windows in msys2 I'm getting this: https://pastebin.com/Rt4h0NT5

This might be the relevant line: 

> make: *** No rule to make target '../build/obj/libretro/agb_boot_libretro.c.o', needed by '../build/bin/sameboy_libretro.dll'.  Stop.

I'm trying to build with prebuilt bootroms sourced from the libretro branch on this repo. I'm doing this in a github actions script:

```
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/agb_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/cgb0_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/cgb_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/dmg_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/mgb_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/sgb2_boot.bin
        wget https://github.com/LIJI32/SameBoy/raw/libretro/BootROMs/prebuilt/sgb_boot.bin
        mkdir -p build/bin/BootROMs
        mv *.bin build/bin/BootROMs
        cd libretro
        make -j8 BOOTROMS_DIR=build/bin/BootROMs
```

I tried it without the BOOTROMS_DIR= too, with the same error.

**Comment by LIJI32** [comment]
I'll have a look! Does this happen specifically with the Windows build? Or does it also happen in other builds? Does it work if you give `BOOTROMS_DIR` and absolute path?

**Comment by Awakened0** [comment]
I've only tried the Windows build. I haven't tried giving the `BOOTROMS_DIR` an absolute path, but I'll see if I can figure it out. Since I'm trying to do it over github actions instead of locally, I'm not fully sure what the directory structure looks like. My build script is over [here](https://github.com/Awakened0/SameBoy-libretro-Builds/blob/main/.github/workflows/main.yml). 

I'm trying to build this myself again since the libretro buildbot seems to be using an outdated build. If you download it from [here](https://buildbot.libretro.com/nightly/windows/x86_64/latest/sameboy_libretro.dll.zip) it's a 0.15.4 build.

**Comment by Awakened0** [comment]
Ok, I got the absolute path correct by using the `pwd` command and now it builds! Previously, as long as I moved the bootroms to build/bin/BootROMs it would build.

I'm not sure if the libretro buildbot was updated to pull from this upstream repo yet or not. But maybe the build is failing on their end because of not providing an absolute path.

**Comment by Awakened0** [comment]
Mentioned the absolute path requirement to libretro folk. They haven't switched their build CI to use this repo yet, but will soon.
