### ISSUE TITLE
Gamepad stops working when enabling gamelink

### ISSUE THREAD

**Issue by jmolero** [LIJI32/SameBoy#532]
I recently tried connecting two instances with gamelink and the gamepad stops working after that and can't do any movements. The keyboard key continue to work however.

It works again if setting the connectivity back to none.

**Comment by jmolero** [comment]
Yes, that was the issue. When connecting the gamelink an unknown gamepad was assigned. After switching back to the right controller the problem is gone and I cannot reproduce it again either. I think the controller settings were pointing to a controller I no longer use.

Thank you!

**Comment by LIJI32** [comment]
Great, so the linked commit should fix the issue entirely in 0.16. Closing.
