### ISSUE TITLE
WilbertPol's mooneye-gb tests failing

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#54]
Once again latest linux autoupdated. Link to sources: https://github.com/wilbertpol/mooneye-gb/tree/master/tests

Fails:
tested in GBC mode:
intr_2_mode0_timing_sprites
intr_2_mode0_timing_sprites_nops
intr_2_mode0_timing_sprites_scx1_nops
intr_2_mode0_timing_sprites_scx2_nops
intr_2_mode0_timing_sprites_scx3_nops
intr_2_mode0_timing_sprites_scx4_nops
ly_lyc_0_write-C
ly_lyc_153_write-C
ly_lyc_write-C
stat_write_if-C
tested in GB mode (just GS/G specific):
ly_lyc_0_write-GS
ly_lyc_153_write-GS
ly_lyc_write-GS
stat_write_if-GS

**Comment by LIJI32** [comment]
That was tested against the libretro core, right? The libretro fork seems to be ~50 commits behind at the moment, so I'd have to test it with the latest code, and again, confirm the CGB results against my CGB-E, as CGB-C and older revisions have an extra PPU bug.

**Comment by sczther** [comment]
Yep, didn't build myself

**Comment by LIJI32** [comment]
Tested all of these tests on the latest master, as well as all intr_2_mode0_* tests.

The following tests pass on both DMG and CGB mode:
 * intr_2_mode0_timing_sprites
 * intr_2_mode0_scx1_timing_nops
 * intr_2_mode0_scx2_timing_nops
 * intr_2_mode0_scx3_timing_nops
 * intr_2_mode0_scx5_timing_nops
 * intr_2_mode0_scx6_timing_nops
 * intr_2_mode0_scx7_timing_nops

The following tests pass on CGB mode and fail on DMG mode:
 * intr_2_mode0_scx4_timing_nops
 * intr_2_mode0_scx8_timing_nops
 * intr_2_mode0_timing_sprites

The following tests fail on both:
 * intr_2_mode0_timing_sprites_nops
 * intr_2_mode0_timing_sprites_scx1_nops
 * intr_2_mode0_timing_sprites_scx2_nops
 * intr_2_mode0_timing_sprites_scx3_nops
 * intr_2_mode0_timing_sprites_scx4_nops

The rest of the tests fail as reported. I still have to confirm those on real hardware, but these should be useful.

**Comment by LIJI32** [comment]
Funny, seems like `intr_2_mode0_scx4_timing_nops` and `intr_2_mode0_scx8_timing_nops ` require an original boot ROM to pass. I wonder what's my DMG boot ROM is doing wrong, as these test do work with 4 other boot ROMs tested.

**Comment by sczther** [comment]
Okay, I managed to compile the latest master and these are the results:
CGB Failing
intr_0_timing.gb
ly_lyc_0-C.gb
ly_lyc_0_write-C.gb
ly_lyc_153-C.gb
ly_lyc_153_write-C.gb
ly_lyc_write-C.gb
ly_new_frame-C.gb
stat_write_if-C.gb

DMG Failing
intr_0_timing.gb
intr_2_timing.gb
ly00_mode0_2-GS.gb
ly00_mode1_0-GS.gb
ly_lyc_0-GS.gb
ly_lyc_0_write-GS.gb
ly_lyc_write-GS.gb
stat_write_if-GS.gb
timer_if.gb

So, some intertesting regressions. I guess you will have to ponder a bit more about the details of the implemenatation. Best of luck!

**Comment by sczther** [comment]
I did not retest everything for reggresions, but it probably is down to this now:

CGB Failing
ly_lyc_0-C.gb
ly_lyc_0_write-C.gb
ly_lyc_153-C.gb
ly_lyc_153_write-C.gb
ly_lyc_write-C.gb
ly_new_frame-C.gb
stat_write_if-C.gb

DMG Failing
ly_lyc_0_write-GS.gb
ly_lyc_write-GS.gb
stat_write_if-GS.gb
timer_if.gb

**Comment by LIJI32** [comment]
It's extremely surprising how many different previously undocumented behaviors were discovered by simply fixing tests in this suit. I just discovered a new quirk that also explains several odd behaviors of the OAM interrupt, and while researching that quirk I wrote a new test ROM that discovered a new edge of the DMG STAT bug.

**Comment by sczther** [comment]
Yeah, I found out Wilbert Pol is _Judge, so it has been a journey with his testsuits for at least 11 years. He sure knows his stuff! Glad it helps to advance the understanding of GB hardware.
PS: Do you have a place where your test roms are available?

**Comment by LIJI32** [comment]
I plan releasing them after v0.11

**Comment by LIJI32** [comment]
Tested currently failing as for the latest commit (testing everything for regressions):

CGB:
ly_new_frame-C
ly_lyc_write-C
ly_lyc_153-C
ly_lyc_0_write-C
ly_lyc_0-C
ly_lyc_153_write-C

DMG:
vblank_stat_intr-GS
ly_lyc_write-GS
ly_lyc_0_write-GS

**Comment by LIJI32** [comment]
All DMG tests pass now. Some more research is needed for the CGB variant of the LYC write tests. It is also very likely that these tests are revision dependent, as CGB-CPU-D fixed some quirks with how LYC works.
