### ISSUE TITLE
SameBoy iOS TestFlight?

### ISSUE THREAD

**Issue by Buggem** [LIJI32/SameBoy#542]
I really think SameBoy would do great on iOS but there is no App on the App Store, so I can't get it. I don't have a mac to build it on either. And since it's only in its early stage, and as an avid GameBoy nerd, I'd like to test it. Could you eventually set up a TestFlight link or something similar?

**Comment by LIJI32** [comment]
TestFlight requires a paid developer account and violates Apple's policy anyway. Pre-compiled IPAs are available on a per-commit basis from GitHub's actions page, e.g. https://github.com/LIJI32/SameBoy/actions/runs/4666087058. The iOS IPA and DEB files are inside the macOS artifact (sameboy-canary-macos-latest-clang)

**Comment by Buggem** [comment]
Thanks for the quick response!

**Comment by Buggem** [comment]
@LIJI32 Your idea worked, but the app can't open on my iPad. The logo shows, but the app "Integrity could not be verified"

**Comment by LIJI32** [comment]
How are you installing the app? You need to sign it with your own free Developer Account and install it via [AltStore](https://altstore.io), [Cydia Impactor](http://www.cydiaimpactor.com), or similar.

**Comment by Buggem** [comment]
I'm dragging the app into iTunes, it seemed to work and the icon appears, but it won't open. I'll try signing it myself.
