### ISSUE TITLE
Library access to raw APU channel volumes

### ISSUE THREAD

**Issue by nununoisy** [LIJI32/SameBoy#548]
I'm currently working on a music visualizer program for the GameBoy in Rust, similar to my nsf-presenter project. I wanted to use SameBoy since it has good sound accuracy and is integration-friendly, so I wrapped the SameBoy core into a library crate and created Rust bindings for it with `bindgen`. I've verified that it works on Windows (after a lot of pain configuring `rust-cc` to use MSBuild+Clang), but I imagine that it would also work on Unix-y platforms without too much work.

I would like to visualize the channels by providing oscilloscope views of each channel as well as a piano roll (similar to Synthesia/other MIDI visualizers). To that end, it would be incredibly convenient to have access to the APU samples for each individual channel before mixing as well as a way to determine the fundamental frequency/pitch of the channel.

This should all be *technically* possible now if I use CGB mode w/ direct accesses to the IO registers:
- Channel volumes from `PCM12`/`PCM34` registers
- Frequencies from calculations on `NRx3` registers (not sure how the wave channel will work yet)

However, it would be far nicer to be able to access this data more directly, and have the ability to access it on anything that isn't a CGB. I'm not sure if it would be easier to add methods to directly query the APU (so one could sample at their leisure), add a new callback (so samples could be buffered during a `GB_run_frame()`), or something else entirely.

**Comment by nununoisy** [comment]
I went ahead and implemented a hacky version of the setup using APU registers with a memory write callback for the `NRx1`/`NRx3`/`NRx4` registers and a couple of `GB_safe_read_memory()` calls for the `PCM12`/`PCM34` registers. It doesn't quite have all the features I need, unfortunately. However, it has shown me what an API could look like for most usecases like mine. Here's a hypothetical interface:

```c
typedef enum {
    GB_DUTY_CYCLE_12_5,
    GB_DUTY_CYCLE_25,
    GB_DUTY_CYCLE_50,
    GB_DUTY_CYCLE_75
} GB_duty_cycle_t;

typedef enum {
    GB_CHANNEL_PAN_NONE,
    GB_CHANNEL_PAN_L,
    GB_CHANNEL_PAN_R,
    GB_CHANNEL_PAN_L_R
} GB_channel_pan_t;

// Pre-mixer channel volume
uint8_t GB_get_channel_amplitude(GB_gameboy_t *gb, GB_channel_t channel);

// Value of the 11-bit period (NRx3/NRx4)
uint16_t GB_get_channel_period(GB_gameboy_t *gb, GB_channel_t channel);

// Channel 1/2 duty cycle
GB_duty_cycle_t GB_get_square_duty_cycle(GB_gameboy_t *gb. GB_channel_t channel);
// Channel 3 wavetable -> user allocated array
void GB_get_apu_wavetable(GB_gameboy_t *gb, uint8_t *wavetable);
// Channel 4 LFSR short mode
bool GB_get_noise_short_mode(GB_gameboy_t *gb);

// Channel stereo pan (NR51)
GB_channel_pan_t GB_get_channel_pan(GB_gameboy_t *gb, GB_channel_t channel);

// Check if the channel's period counter rolled over since the last time we checked, for edge-triggering.
bool GB_channel_period_ended(GB_gameboy_t *gb, GB_channel_t channel);
```

This should be enough information to display the following:
- Oscilloscope view of each channel from the amplitude data, centering the wave based on the edge trigger flag.
- Piano roll, based on frequencies calculated from the period lengths.
- Pseudo-instruments based on:
  - Square: duty cycle
  - Wave: some sort of hash on the wavetable
  - Noise: LFSR short mode
- Stereo panning information.

If this interface looks good to you, I can start working on a PR to get it in. If you have any critiques, feel free to make them known - I'm not too attached to this particular design.

**Comment by LIJI32** [comment]
Looks good to me, however some APIs feel a bit redundant when they can be replaced by a simple `GB_safe_read_memory` call (duty, pan, period and LFSR length). Other APIs look good as they indeed expose information that is normally not accessible or require a bit of extra code to obtain (current volume, current PCM amplitude outside of CGB mode, nibble-splitting the wave table...). Could you explain the purpose of the `GB_channel_period_ended` API? I'm rather confused by what should it be used for.

**Comment by nununoisy** [comment]
The square/wave channel period values are masked away in `GB_apu_read()` so an API method would be necessary to access them. The others can be replaced with `GB_safe_read_memory()` calls, though I included them here so they could be mapped to enum values or just for clarity - I can remove them if you wish.

The edge triggering functionality is useful for centering oscilloscope waveforms on a period boundary:
- Pulse channels: the rising edge of a square wave
- Wave channel: the beginning of first sample in the wavetable
- Noise channel: the resetting of the length timer
As I see it, this functionality would require a bit of extra tracking in the form of a bool per channel struct that is set when the edge condition is triggered and cleared when queried.

**Comment by nununoisy** [comment]
#549 was merged so this is resolved.
