### ISSUE TITLE
Documentation about command line arguments

### ISSUE THREAD

**Issue by guilherssousa** [LIJI32/SameBoy#559]
Where can I find information about available command line arguments? I know I can pass a path to a game ROM and it will open Sameboy immediately loading the game, but what about others? I'm trying to launch the emulatior with a ROM and its save data from different places via a single command.

**Comment by orbea** [comment]
This is all I see:
```
$ ./sameboy --help
SameBoy v0.15.8
Usage: ./sameboy [--fullscreen|-f] [--nogl] [--stop-debugger|-s] [--model <model>] <rom>
```
