### ISSUE TITLE
Graphical issues with demo "It Came from Planet Zilog"

### ISSUE THREAD

**Issue by ParzivalWolfram** [LIJI32/SameBoy#56]
There are some minor graphical problems for most of the demo, but during a specific part right at the end there are SEVERE graphical issues and a severe timing issue. BGB and Gambatte do not exhibit these issues.

Demo:
www.pouet.net/prod.php?which=65345

How to Reproduce:
1. Load the ROM
2. Be observant

**Comment by LIJI32** [comment]
Problems are the priority issues with the Spaceship scene and that one last scene with completely wrong colors, am I missing anything else?

**Comment by ParzivalWolfram** [comment]
The priority issues are present during the Spiraling scene as well, but yes.

**Comment by LIJI32** [comment]
I just tested this ROM on my own CGB and the only difference I could find is the corrupt palette. The priority issues and the visual glitches in the spiraling scene appear on real hardware as well, unless I misunderstand the issue. Screenshots would be helpful.

**Comment by ParzivalWolfram** [comment]
I'm having trouble with that, as they're really hard to time. I'm
attempting to do a side-by-side video comparison with BGB, but i'm not
experienced with any video editors. The portion that has the corrupt
palette is quite broken, actually, as parts of the image are supposed to
fade in over time instead of doing a fast sideways slide-in like shown in
Sameboy. I'd recommend a side-by-side comparison with BGB to see what I
mean.
