### ISSUE TITLE
Controller not detected if connected while SameBoy is running.

### ISSUE THREAD

**Issue by aljohnston112** [LIJI32/SameBoy#563]
Controller works fine if the controller is connected while SameBoy is running. Kind of annoying when your controller disconnects sometimes.

**Comment by carmiker** [comment]
@aljohnston112 if you are referring to the SDL build, I have the answers on a silver platter right here: https://github.com/carmiker/sdl2-hotplug-example
If you're talking about macOS then I do not have the answers.

**Comment by LIJI32** [comment]
Correct me if I'm wrong, I'm not sure I understand the issue correctly.
Your issue is that on the non-Mac version, the controller does not work if it has been disconnected and reconnected again?
