### ISSUE TITLE
X11 vs MIT License

### ISSUE THREAD

**Issue by carmiker** [LIJI32/SameBoy#574]
@LIJI32 I notice you've changed the license from MIT to X11, however there is an extra clause in the X11 license that was not added to the text in LICENSE and ios/License.html:

Sources:
https://spdx.org/licenses/X11.html
https://en.wikipedia.org/wiki/MIT_License#X11_License

**Comment by LIJI32** [comment]
Ah, good catch, I got it mixed up with Expat (which doesn't have this extra clause), I'll have it fixed. Thanks!

**Comment by carmiker** [comment]
@LIJI32 now you have the X11 license, but listed as Expat (except for `LICENSE` which is actually Expat). The other instances are now X11.
Expat == MIT
X11 == MIT + No Advertising clause (which results in more or less the same terms as the BSD 3-Clause)
