### ISSUE TITLE
iOS app crashes on launch (iOS Simulator)

### ISSUE THREAD

**Issue by Buggem** [LIJI32/SameBoy#575]
https://github.com/LIJI32/SameBoy/assets/66670928/2c4805f2-05d4-41d7-be3b-8bfe62b4ed9f

iOS 16.1 iPad Mini, however any other device or operating system yields the same result... as usual system logs (Console) prove no help at all.

I'm sorry the screen recording is very low quality, I hope you understand I needed to compress it to upload.

**Comment by LIJI32** [comment]
iOS apps need to be specifically built to run on the iOS simulator. SameBoy for iOS is only built to run actual iOS devices. It might work on ARM-based Macs (Never tested such thing, so I'm not sure), but it definitely wouldn't work on an Intel Mac.
