### ISSUE TITLE
Menu texts are not cleaned when I go back from SGB border

### ISSUE THREAD

**Issue by sdhizumi** [LIJI32/SameBoy#580]
I found a bug that menu text and cursor icon are not cleared (remained) when I move cursor or switch menu to another layer.
It is happening when I go back to the option menu from game which it is show SGB border.

I tested SameBoy v0.16.1 on Windows (sameboy_winsdl_v0.16.1.zip from github release page)

Note: It is not happen in v0.15.8 (This version is left in my local.)
![image](https://github.com/LIJI32/SameBoy/assets/31327231/86d1f3e0-ee12-4570-bbf0-85a5d9a65580)

**Comment by LIJI32** [comment]
Duplicated of #576, which has been fixed for 0.16.2 (Should be released this weekend)
