### ISSUE TITLE
Quick Look preview generator appears to be broken

### ISSUE THREAD

**Issue by SamusAranX** [LIJI32/SameBoy#581]
I'm using SameBoy 0.16.1 on macOS Sonoma 14.2.1.

In the past, opening Quick Look on a ROM used to display a cartridge icon containing a screencap, but now, there's just transparency where the screencap used to be. Is there anything I can do about this or is this a known problem?

<img width="921" alt="Screenshot 2024-01-10 at 18 33 07" src="https://github.com/LIJI32/SameBoy/assets/676069/77a0a6fc-c2f0-4846-87c9-be10ca8847d2">

**Comment by LIJI32** [comment]
Managed to reproduce this on my Sonoma VM, I'll have a look. Thanks!

**Comment by Buggem** [comment]
This also affects me on macOS Sonama. Hope it gets fixed soon.
