### ISSUE TITLE
Graphical issues when opening the menu

### ISSUE THREAD

**Issue by Adamillo** [LIJI32/SameBoy#584]
I found a weird bug. This only happens if one of 2 conditions meet:
1. The game runs in SGB Mode, doesn't matter if it's SGB NTSC, PAL or SGB2
2. The SGB border are displayed
If one of these conditions meet, the menu doesn't display properly. Here's video footage of this weird issue. EDIT: It seems that Sameboy version 0.15.8 displayed the menu just fine, so it seems like this is a regression

https://github.com/LIJI32/SameBoy/assets/45568316/447418b0-0273-4f82-b1d8-17b26fb4755c

**Comment by LIJI32** [comment]
This has been fixed in version 0.16.2, which was released a few minutes ago.
