### ISSUE TITLE
'TEST SRAM ERROR' on game "Crazy Richman 2 (J) [C][!]"

### ISSUE THREAD

**Issue by Buggem** [LIJI32/SameBoy#585]
In the [automations](https://sameboy.github.io/automation/#:~:text=Crazy%20Richman%202%20(J)%20%5BC%5D%5B!%5D) page, I found this strange error that did not appear as a failure. Here is an image of the error. It appears to be coming from the game itself rather than the logs. ![image](https://github.com/LIJI32/SameBoy/assets/66670928/cbf10a9f-9068-40d4-aace-401c600f428d)

**Comment by LIJI32** [comment]
Good catch! This is an unlicensed game that seems to have contradictions in its ROM header, I'll add a fix to handle such cases.
