### ISSUE TITLE
package SameBoy core

### ISSUE THREAD

**Issue by gogo2464** [LIJI32/SameBoy#586]
Hello,

I need to use the sameboy core for gb for a research project on glitch. I want to create a new algo to find glitch. My algo will be based on the states after inputs. I do not need any graphics.

Could you package sameboy core as a library please? 

You can pick the os you want! My project is coming.

Best regards.

**Comment by orbea** [comment]
What exactly does glitch want?

You can build `libsameboy.a` with `make lib`, but I am not sure if that is what you want?

**Comment by gogo2464** [comment]
I mean to assist speedrun. I will try your method.

thanks
