### ISSUE TITLE
Mooneye GB tests

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#59]
Fails in latest master:
DMG mode:
acceptance:
boot_hwio-dmgABCXmgb
serial:
boot_sclk_align-dmgABCXmgb
CGB mode:
misc:
boot_hwio-C

I guess the boot_hwio tests pass with official bootroms?

**Comment by LIJI32** [comment]
`boot_sclk_align` requires official boot ROMs to pass (It literally depends of the number of cycles to boot took). All boot tests (both regs and hwio) pass with the official bootROMs, but I should fix those anyway. The MBC1 tests are a regression, they used to pass before.

**Comment by LIJI32** [comment]
BTW, thanks for all these bug reports, they're really helpful. :)

Also, are you using the automated tester for these?

**Comment by LIJI32** [comment]
Mmm, the MBC1 tests seem to work for me.

**Comment by sczther** [comment]
Nope, haven't dabbled with the autotester yet, I thought of adapting it for the Gambatte test suite (not doing that by hand :D). But the smaller testsuites often need different methods of checking. I guess I should have a look at how it works.

**Comment by LIJI32** [comment]
Basically it just runs a ROM for X seconds and takes a screenshot. You can give it several ROMs and it'll test them all.

**Comment by sczther** [comment]
The MBC1 tests pass on my side now too, did a clean rebuild. I guess that it was caused by copying several versions over each other?

**Comment by LIJI32** [comment]
Might be, but the MBC1 test ROM have been passing for at least a few months now... =/

**Comment by sczther** [comment]
Well, it works, that's important. I will be sure to investigate more if it ever happens again.

**Comment by sczther** [comment]
Still the DMG tests ;)

**Comment by LIJI32** [comment]
The remaining DMG tests can't pass without the original boot ROMs (and they indeed do when using them), both depend on the actual number of cycles the boot took – this level of accuracy can't be achieved with SameBoy's boot ROMs.

**Comment by LIJI32** [comment]
The CGB version of `boot_hwio` passes only because it does check the `DIV` register, as the length of the CGB boot varies by various factors – the ROM's header and user input.

**Comment by sczther** [comment]
Oh, that makes sense. I thought how you could fix the GBC one, but it makes sense, with the palette stuff.
