### ISSUE TITLE
Donkey Kong (94) Post Level Scoreboard Doesn't Show

### ISSUE THREAD

**Issue by Awakened0** [LIJI32/SameBoy#6]
After you finish a level, the area where the scoreboard should be at the bottom of the screen is blank:
![clipboard-1](https://cloud.githubusercontent.com/assets/4565863/25765928/9500b2da-31bd-11e7-883b-61445d42cc2d.png)

Tested in the 0.8 Windows SDL release, but I first noticed it in the new libretro core.

**Comment by LIJI32** [comment]
I'm currently away from home but I believe this has something to do with enabling the window mid-scanline. I'll proably fix it next week.
