### ISSUE TITLE
How to add fast forward & rewind to trigger buttons?

### ISSUE THREAD

**Issue by goodstuff626** [LIJI32/SameBoy#605]
How to add fast forward & rewind to ps4 trigger (L2 R2 buttons) ? I was able to set this up before using my ps3 controller, but I got a new ps4 controller and need to set up the input buttons on sameboy again, and can't figure out how to add fast forward & rewind buttons to L2 R2. Please help.

**Comment by LIJI32** [comment]
In the macOS version, click SameBoy > Preferences, and select the Controls tab, then click "Configure a Controller" and follow the instructions.

In the SDL version, press Escape to open the menu, then select Options > Control Options > Joypad Options > Configure layout, and follow the instructions.
