### ISSUE TITLE
Blinking sprites on some games

### ISSUE THREAD

**Issue by meganekko** [LIJI32/SameBoy#61]
Since commit https://github.com/LIJI32/SameBoy/commit/d8e0683c3597f3f1fede037e471d6f126e54e104 and up, the emulator displays blinking sprites on some games. The effect happens specially when moving, if that makes sense. I have recorded the following two videos as a reference:

Wario Land - Super Mario Land 3 (W) [!].gb: https://0x0.st/sMCA.mp4
Kirby's Dream Land 2 (U) [S][!].gb: https://0x0.st/sMCm.mp4

SameBoy was compiled using libsdl2-dev 2.0.7+dfsg1-3 and clang 4.0-40 on Debian sid. 

Thank you for making such great emulator! 🌟

**Comment by LIJI32** [comment]
Yeah I just noticed this bug yesterday I haven't got a chance to fix it yet. I'll fix it in a few minutes. :)
