### ISSUE TITLE
Build fails on Linux ARM

### ISSUE THREAD

**Issue by Mailaender** [LIJI32/SameBoy#611]
> clang-16: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]

https://buildbot.flathub.org/#/builders/42/builds/10520/steps/7/logs/stdio

**Comment by LIJI32** [comment]
`-fstack-clash-protection` isn't a flag coming from SameBoy, it seems to be coming from a script invoking SameBoy's Makefile. I'm not sure where exactly it comes from, but adding `-Wno-unused-command-line-argument` right before it should solve it. (Alternatively, you could remove it altogether if you care about speed more than security mitigations)

**Comment by Mailaender** [comment]
You are correct. I can fix this without a patch.
