### ISSUE TITLE
ROM files cannot be imported

### ISSUE THREAD

**Issue by AriiRafiq** [LIJI32/SameBoy#621]
![IMG_9335](https://github.com/LIJI32/SameBoy/assets/25040328/1a67445d-5934-43f7-82f6-21bb0b4f9b46)

**Comment by LIJI32** [comment]
I’m looking into this problem, it’ll be fixed in a few days. Meanwhile, you can work around this problem by importing ROMs from the Files app. Long press a ROM, tap Share, and select SameBoy.

**Comment by LIJI32** [comment]
Fixed in 0.16.5.
