### ISSUE TITLE
Iphone

### ISSUE THREAD

**Issue by Druffgschisse** [LIJI32/SameBoy#622]
1. Import doesnt work
2. Rom share to sameboy work, but after this cant close the rom. After closing the app SameBoy, the last rom is loaded and play. Cant close it anymore. Would change the emulator but there is no options anymore after the rom shareing

**Comment by LIJI32** [comment]
1. This is a known issue and will be fixed in the next few days.
2. You don't need to close the ROM to switch a game,  just tap the screen to open the menu again, then you can change to another imported ROM from the Library.

**Comment by LIJI32** [comment]
Fixed in 0.16.5.
