### ISSUE TITLE
Associate ROM files with SameBoy on Windows

### ISSUE THREAD

**Issue by Rangi42** [LIJI32/SameBoy#643]
This *could* be done by having the user run a .reg or .bat file; that's what I do for [Polished Map](https://github.com/Rangi42/polished-map/blob/master/install.bat). ([See also](https://github.com/Rangi42/polished-map/issues/85))

I believe this C code will be the equivalent:

```c
bool set_registry_string(HKEY hive, const char *folder, const char *name, const char *value) {
	HKEY hkey;
	LONG status = RegCreateKeyExA(hive, folder, 0, NULL, 0, KEY_ALL_ACCESS, NULL, &hkey, NULL);
	if (status != ERROR_SUCCESS || hkey == NULL) {
		return false;
	}
	status = RegSetValueExA(hkey, name, 0, REG_SZ, value, strlen(value) + 1);
	RegCloseKey(hkey);
	return status == ERROR_SUCCESS;
}

	set_registry_string(HKEY_CURRENT_USER, "Software\\Classes\\.gbc", "", "SameBoy");
	set_registry_string(HKEY_CURRENT_USER, "Software\\Classes\\SameBoy", "", "Game Boy Color ROM");
	set_registry_string(HKEY_CURRENT_USER, "Software\\Classes\\SameBoy\\shell\\open\\command", "", "\"C:\Programs\SameBoy\sameboy.exe\" \"%%1\"");
```

(Of course SameBoy should figure out the right .exe path to pass for the `open` command. And you might use the W or A or neither functions, not sure if SameBoy is used to using wide strings or not.)

**Comment by LIJI32** [comment]
I'll give it a look, if I get it working I'll also add the cartridge icons in Windows .ico format.
(SameBoy internally wraps `fopen` and co. to use UTF-8 strings for source compatibility with every other OS)

**Comment by LIJI32** [comment]
More thoughts:
1. Is there a way to do this *less* aggressively? i.e. don't overwrite existing associations.
2. How would I associate a specific icon resource with these types?
3. Can I add myself as a "valid open handler" for a file without "stealing" the default handler for a file type?

**Comment by Rangi42** [comment]
1. Check if `"Software\\Classes\\.gbc"` already exists with `RegOpenKeyEx`, and if so, ask the user whether to continue?
2. Create `HKCR\SameBoy\DefaultIcon` and set it to the .ico path. (Or to use e.g. icon -42 within an EXE or DLL, you can do `sameboy.exe,-42`.)
3. Add sameboy.exe to `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.gbc\OpenWithList`.

**Comment by LIJI32** [comment]
Done and implemented, thanks!
