### ISSUE TITLE
libretro Makefile will need an update to support new Wii U toolchain

### ISSUE THREAD

**Issue by vaguerant** [LIJI32/SameBoy#645]
libretro/RetroArch#14925 will be updating RetroArch to compile with the modern Wii U toolchain instead of the old version with which it builds currently. In the time since libretro updated the toolchain, the `-mwup` flag was removed from the compiler. Over on the libretro fork, @Ploggy has submitted a PR libretro/SameBoy#91 which has already been merged. This change supports both toolchain versions. I'm not sure how actively libretro support and development occurs here in upstream, so just covering all bases in case you want to merge that over here also.

**Comment by LIJI32** [comment]
This is a bit odd, the libretro fork of SameBoy shouldn't be maintained anymore AFAIK (It hasn't pulled from upstream in over 2 years), the libretro buildbot is using the libretro branch of this repo. I'll commit the patch but I'll also have to see what's going on with that repo.
