### ISSUE TITLE
Pokémon brown color scheme

### ISSUE THREAD

**Issue by JD9871** [LIJI32/SameBoy#646]
Hello I had a question regarding the color scheme for Pokémon brown. This images is what the game should look like ![image](https://github.com/LIJI32/SameBoy/assets/164794137/60672586-f0ef-4f88-ae37-c8c2933bc19a) whereas mine is coming out like this ![image](https://github.com/LIJI32/SameBoy/assets/164794137/b93dd804-73e1-45ac-b3a4-a0de77657215) I have gameboy color set as the model and have tried all cpu cores including experimental ones. My video settings are posted but I have tried all options as well ![image](https://github.com/LIJI32/SameBoy/assets/164794137/eda16668-6e57-4de1-aebb-a2b3ea6ce52a) I'm referencing a post I found regarding this issue and using mGBA resolved the issue but I have no way of testing that https://www.reddit.com/r/PokemonROMhacks/s/oDKJItVv8J

**Comment by LIJI32** [comment]
The original Gen 1 Pokémon games, with the exception of western Pokémon Yellow, are Super Game Boy, not Game Boy Color games. This probably applies to this hack as well. Try changing the emulated model to SGB.

**Comment by JD9871** [comment]
> The original Gen 1 Pokémon games, with the exception of western Pokémon Yellow, are Super Game Boy, not Game Boy Color games. This probably applies to this hack as well. Try changing the emulated model to SGB. 

I know but it's meant to be played on gbc hardware. It came out over a decade ago when the only options were VBA-M and mGBA. Setting it to super gameboy did help but the palette reverts back for some reason ![image](https://github.com/LIJI32/SameBoy/assets/164794137/1ce150c3-0490-4947-b85a-bd0374f6debd)![image](https://github.com/LIJI32/SameBoy/assets/164794137/a2736d6d-773b-41db-b311-a8ccb65fe4f4)

Starting off the palette is correct but exiting causes the color to shift to that shade of blue

**Comment by JD9871** [comment]
Weird. Issue resolved after reboot using SuperGameboy 2 option? I changed and reset the game but nothing happened. Either way it works now thank you for your responses ![image](https://github.com/LIJI32/SameBoy/assets/164794137/dffc7fec-ea9b-440a-b74c-f0b3e57f547b)

**Comment by JD9871** [comment]
Set to SuperGameboy 2 then reboot (even after reset) and color fixed
