### ISSUE TITLE
Requesting a new iOS release for the multi-lens camera feature

### ISSUE THREAD

**Issue by logicalmoody** [LIJI32/SameBoy#649]

**Comment by jarbochov** [comment]
Seconded. Very much looking forward to this feature and sharing the app.

**Comment by logicalmoody** [comment]
@LIJI32 if you have a release timeframe in mind, could you share? Thanks!

**Comment by LIJI32** [comment]
The next major of SameBoy is around 75% done, and is scheduled for release in early 2025. However, I might release a last minor for the 0.16.x line in the next few weeks.
