### ISSUE TITLE
Doesn't render black pixels when CPU is changing palette while PPU is reading it

### ISSUE THREAD

**Issue by mattcurrie** [LIJI32/SameBoy#65]
[game.gb.zip](https://github.com/LIJI32/SameBoy/files/1905925/game.gb.zip)

Hi there,

Was sent here by @ISSOtm :)

The attached test rom switches from one palette to the inverse of that palette and then back to the original palette during mode 3. There are 12 t-cycles between palette changes:

```
    ; set the new palette: 8 cycles
    ld [c], a

    ; set the old palette again: 12 cycles
    ld a, b
    ld [c], a
```

In an earlier version of the test rom I was just switching the palette from white to black to white on each line, and thought it was a timing issue with the ® sprite, but PinoBatch suggested testing black to white to black also. "When one component writes a value at the exact time something else reads it the time for the value to rise may differ from the time for it to fall. A 1 may linger longer than a 0 or vice versa."

Not 100% sure whats going on, but seems like if the CPU is changing the palette while the PPU is reading the palette on the same cycle then the pixel should be rendered as black (or dark grey?). 

The effect isn't seen on my MGB or CGB, only on DMG.

Screenshot taken from a build from master:
<img width="272" alt="screen shot 2018-04-13 at 6 00 51 pm" src="https://user-images.githubusercontent.com/455505/38719172-a52b90f4-3f44-11e8-9209-4cb4036fde46.png">

Dusty screen photo:
![image](https://user-images.githubusercontent.com/455505/38719130-747efb9e-3f44-11e8-9ea6-7c4ec537855f.jpg)

**Comment by LIJI32** [comment]
Not only this is extremely interesting, it is hard to describe how useful it is for T-cycle accurate measurements of Mode-3. Do you know which DMG CPU is it? Does it pass dmg_sound-2? Is this effect visible in Prehistorik Man's title screen? It does pretty much the same thing. Does this occur when you use different values (e.g. write the same value twice, write two different but non-inverted palettes)? This is so unfortunate I only have a CGB and SGB2 (which is effectively an MGB).

**Comment by mattcurrie** [comment]
Ok so I've got 2 DMG's here and both exhibit this same behavior:

Red:
Passes dmg_sound-2
Mainboard: DMG-CPU-08

Blue:
Fails test 10 on dmg_sound-2
Mainboard: DMG-CPU-06

Writing the same palette value during mode 3 doesn't cause any of the black pixels. Will try some more tests with different non-inverted palettes.

I've recorded some video of Prehistorik Man and it looks like the black edges are just slightly visible on the edges of the large text on the title screen:

![img_4525](https://user-images.githubusercontent.com/455505/38736176-53af28f4-3f7f-11e8-8880-7a51f33549d6.jpg)
![img_4524](https://user-images.githubusercontent.com/455505/38736177-5656a5aa-3f7f-11e8-9927-c3b92a0560ec.PNG)

Different alignment for the large text and no black edges on backlit CGB:
![img_4523](https://user-images.githubusercontent.com/455505/38736214-790f2220-3f7f-11e8-81be-4bdae019fedb.PNG)

**Comment by LIJI32** [comment]
I meant the actual revision of the CPU chip (It should say something like DMG-CPU B) but if red one passes dmg_sound-2 it means it's a DMG-CPU B (or the equivalent blob variant). My guess is that the value read by the PPU in that moment is the result of a bitwise AND operation between the old and new version. It is possible that other PPU registers are affected by this quirk, I'll have to take these all into account when I implement PPU-CPU conflicts properly.

**Comment by mattcurrie** [comment]
Ah yep, so I've now opened up the DMGs:

Red:
Passes dmg_sound-2
Mainboard: DMG-CPU-08
CPU: blob (?)

Blue:
Fails test 10 on dmg_sound-2
Mainboard: DMG-CPU-06
CPU: DMG-CPU B

**Comment by LIJI32** [comment]
That's... annoying. This means I have to reverify a lot of T-cycle timings on an actual DMG.
