### ISSUE TITLE
Rumble does not work on windows

### ISSUE THREAD

**Issue by M00nBr1ght** [LIJI32/SameBoy#650]
I have not found any way to test or configure rumble and it does not work when I use a rumble compatible game. I currently have it set to rumble mode all games.

**Comment by LIJI32** [comment]
Rumble support on the SDL version depends on various factors, including SDL's rumble support for your specific controller. What controller are you using?

**Comment by M00nBr1ght** [comment]
8-bitdo ultimate wireless controller blutooth

**Comment by LIJI32** [comment]
Unless I missed something, it seems that SDL does not provide rumble support for this controller. I would suggest asking for this feature in [SDL's repository](https://github.com/libsdl-org/SDL).
