### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by mirko93s** [LIJI32/SameBoy#670]
All I get is a black screen. Maximizing the window allows to see the menu for a frame or two sometimes, before going to all black again.
I managed to load roms clicking random buttons and I could hear sounds but nothing on the screen, still.
I'm on win11 24h2, I don't know if this could be related.

![image](https://github.com/user-attachments/assets/30519ba0-3a74-401c-ab3d-a5afcfc87f6b)

**Comment by LIJI32** [comment]
Are you using an Intel HD GPU by chance?

**Comment by mirko93s** [comment]
rx570 paired with an old i7 3770

**Comment by LIJI32** [comment]
Can you check if running SameBoy from cmd.exe with `--nogl` (e.g. `C:\Path\To\SameBoy.exe --nogl`) lets you view the screen? Can you also verify the integrated Intel HD Graphics 4000 card isn't in use somehow? Intel HD GPUs tend to have *a lot* of OpenGL driver issues.

Also, can you upload your `prefs.bin` file from `C:\Users\USER\AppData\Roaming\SameBoy`?

**Comment by mirko93s** [comment]
`--nogl` works. The integrated gpu is disabled so that shouldn't be the cause.
Anyway I think the issue is on my end, I just tried other opengl apps and some of them are just broken now since I updated to 24h2. So it's probably windows or amd drivers causing this.
I'll let you know if I can manage to find the problem.
[prefs.zip](https://github.com/user-attachments/files/17907391/prefs.zip)

**Comment by mirko93s** [comment]
Reinstalled an older driver and now everything works... It was just amd being amd I guess. Thank you for your patience!
