### ISSUE TITLE
The flatpak version isn't updated so I got many crashes/bugs

### ISSUE THREAD

**Issue by sheil1488** [LIJI32/SameBoy#673]
Hello,

The flatpak version isn't updated, and on steam deck, since it's hard to install packages it's our only way to go, please update it to the 1.0 version, it's still in 0.16.5 and so many games doesn't work properly..

**Comment by LIJI32** [comment]
The flatpak package isn't maintained by me, you might want to open an issue at [the flatpak's package repo](https://github.com/flathub/io.github.sameboy.SameBoy)
