### ISSUE TITLE
Missing include in Core/symbol_hash.c

### ISSUE THREAD

**Issue by GrieverV** [LIJI32/SameBoy#73]
SameBoy fails to compile on Alpine Linux/musl libc due to `ssize_t` being used in Core/symbol_hash.c without including either `<unistd.h>` or `<sys/types.h>` headers

```
Core/symbol_hash.c:8:5: error: unknown type name 'ssize_t'; did you mean
      'size_t'?
    ssize_t min = 0;
    ^~~~~~~
    size_t
/usr/lib/clang/5.0.1/include/stddef.h:62:23: note: 'size_t' declared here
typedef __SIZE_TYPE__ size_t;
                      ^
Core/symbol_hash.c:9:5: error: unknown type name 'ssize_t'; did you mean
      'size_t'?
    ssize_t max = map->n_symbols;
    ^~~~~~~
    size_t
/usr/lib/clang/5.0.1/include/stddef.h:62:23: note: 'size_t' declared here
typedef __SIZE_TYPE__ size_t;
                      ^
2 errors generated.
make: *** [Makefile:146: build/obj/Core/symbol_hash.c.o] Error 1
```

**Comment by GrieverV** [comment]
I was reminded of [Include What You Use](https://include-what-you-use.org/) and decided to look into it; sadly I lost interest pretty quickly, but here's what I obtained when I was using SameBoy as a test in case IWYU is ever of interest to you:  

Script I created to quickly test IWYU against SameBoy:  
[https://gist.github.com/GrieverV/01edf2182cfd1c13d85d501c927dc95e](https://gist.github.com/GrieverV/01edf2182cfd1c13d85d501c927dc95e)  
Diff generated using the above script:  
[https://hastebin.com/ikeburusiv.diff](https://hastebin.com/ikeburusiv.diff)  

Some notes:  
 * All ignored files experienced the same error. I lost interest before I remembered to look into it
 * sameboy.imp is a [mapping file](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md) for IWYU
 * IWYU/fix_includes.py can require multiple passes to reach '0' edits
 * IWYU is nowhere near perfect and may not match your preference for handling includes, but it's a useful tool to help check includes (if you can get it to behave)
* Above diff was generated using IWYU [579007a](https://github.com/include-what-you-use/include-what-you-use/tree/579007a32e285360f144b5f143da13c3f2ac3b85) and a recent build of LLVM/Clang svn

**Comment by LIJI32** [comment]
This seems quite useful! The only thing is that it expands "umbrella includes" (`gb.h`, `SDL2.h`). I'll selectively import the relevant fixes and that should be good enough.

**Comment by LIJI32** [comment]
Can you confirm the last commit fixed the compilation issues on your setup so I can close this issue?

**Comment by GrieverV** [comment]
Successfully built 80c92da on my alpine:edge container. Thanks!
