### ISSUE TITLE
(Proposal) GNUStep support for Cocoa UI

### ISSUE THREAD

**Issue by wyatt8740** [LIJI32/SameBoy#77]
This is mostly just a thought and suggestion; I am not sure if it is possible because I have next to zero Cocoa experience.
Would it be possible to port the Cocoa UI to other platforms by using GNUStep? Is there any interest in doing so?
It's not got all of the features of Cocoa, but there's enough that I _think_ it's feasible from what I can glean from the documentation.
Go ahead and close this if you're not interested.

**Comment by LIJI32** [comment]
Not sure how possible it is (Not sure how active GNUStep is and what APIs it actually supports), but I'll keep it open as a "nice to have" feature.

**Comment by wyatt8740** [comment]
Thanks for the quick follow-up. Does Cocoa SameBoy use OpenGL? Does Cocoa care about OpenGL, or is that handled outside of the framework?

(I haven't had a mac in ages and don't program for them much, but I might be interested to try learning some ObjC.)

**Comment by LIJI32** [comment]
Cocoa has `NSOpenGLView` which is an NSView subclass that lets you use OpenGL to render it, which is what SameBoy uses. Also, SameBoy doesn't use Xcode at all (I use a single `make` based build system for all platforms and targets).

**Comment by wyatt8740** [comment]
Well that's excellent then. I should have checked, but typically I just anticipate OS X programs to use XCode (much to my chagrin.)
Looks like GNUStep does support it, which is good. https://github.com/gnustep/tests-examples/tree/master/gui/MyGL

**Comment by wyatt8740** [comment]
Looks like you use Carbon, so unless there's a way to work around it, that kills easy GNUstep compatibility.
I wrote up a small custom Makefile to try to build it and it trips up there. Carbon is not part of the NEXTstep/Openstep framework.
For a more complete list:
http://mediawiki.gnustep.org/index.php/Writing_portable_code

**Comment by LIJI32** [comment]
Carbon is only used for input remapping, which definitely won't work on GNUStep because it also uses private APIs, but this isn't anything major.

**Comment by LIJI32** [comment]
Correct me if I'm wrong, but it seems that GNUStep is missing AudioToolbox? If so, this makes audio output impossible.

**Comment by paulwalker-dev** [comment]
Is there any future plans to implement this?

**Comment by LIJI32** [comment]
I did look into it a few months ago, GNUStep and related projects are lacking even in basic AppKit support. The best I could get is a single window with a menu bar (that didn't even work); no audio or video what-so-ever, and since menus (and keyboard shortcuts) didn't work either, I have no way to interact with anything. I'm closing this as it seems that GNUStep (and derived projects e.g. Cocotron) isn't reaching a state where it's usable for porting any non-trivial macOS app any time soon.
