### ISSUE TITLE
couple of demos that dont work

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#82]
FREEART Intro V2 (PD) [C]
blank screen

Minesweeper for 'Windows' (PD) [C]
freezes up when you start a new game

MainBlow (PD) [C]
the spinning fan graphics are glitched

Green Beret (PD) [C]
blank screen

**Comment by LIJI32** [comment]
FREEART V2 seems to have several bugs that make it only work on certain flash carts. It also jumps to uninitialized RAM which is non-deterministic.

**Comment by LIJI32** [comment]
Forcing a [$0000]=$0a write at startup (which the original ROM is missing) fixes this ROM, but this is incorrect.

**Comment by LIJI32** [comment]
`MainBlow (PD) [C]` looks the same on my CGB

**Comment by LIJI32** [comment]
"Green Beret (PD) [C]" has the same issue as "FREEART Intro V2 (PD) [C]", both assume the cartridge RAM is initially unlock, which is only correct for EMS flash carts. Both will fail on real hardware if they're flashed onto carts properly emulating MBC1 or MBC5.

"Minesweeper for 'Windows' (PD) [C]" relies on uninitialized RAM and freeze if it's initialized to all zeros. Proper RAM initialization fixes it.

**Comment by benderscruffy** [comment]
could you add an option to emulate EMS flash carts later on

**Comment by benderscruffy** [comment]
MainBlow (PD) [C] looks the same on my CGB
just wondering why it looks like it is working properly in kigb

**Comment by LIJI32** [comment]
> could you add an option to emulate EMS flash carts later on

While not complicated to emulate, it is impossible to automatically detect ROMs that were designed for EMS flash carts, I'd rather avoid GUI options that fix some ROMs and break others. For the same reason, games using unofficial mappers are currently non-goals.

> just wondering why it looks like it is working properly in kigb
KiGB is known to use a lot of game specific hacks to compensate for it's relatively poor accuracy, or improve some games by inaccurately emulating them. For example, it boasts about having no flickering graphics in 3D Pocket Pool compare to other emulators that do have them, but the latter behavior is the correct one that occurs on hardware.

**Comment by benderscruffy** [comment]
ok thanks for the explanation
