### ISSUE TITLE
Galaga - Destination Earth (U) [C][!] buzzing sound

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#85]
during the game you can hear a buzzing sound

**Comment by creambits** [comment]
This bug seems to around since forever maybe. Gambatte and BGB 1.57 don't have this buzzing sound (Triangle); maybe some pops.

**Comment by creambits** [comment]
Remove this line to fix
https://github.com/LIJI32/SameBoy/blob/master/Core/apu.c#L772
