### ISSUE TITLE
Perfect Dark (U) (M5) [C][!] missing speech and sound fx

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#87]
during the developers screens and during gameplay it is missing  speech and sound fx

**Comment by LIJI32** [comment]
This seems like a regression, I'll have to look into it.

**Comment by lacastri** [comment]
broke in this commit
https://github.com/LIJI32/SameBoy/commit/bfb37884e130396a4e215520326354f454651787

endrift discusses this tricky problem here
https://github.com/mgba-emu/mgba/pull/1164
