### ISSUE TITLE
Cannon Fodder (U) (M5) [C][!] continual buzzing sound

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#89]
buzzing sound from developers screen to ingame

**Comment by LIJI32** [comment]
The way Cannon Fodder plays PCM audio  heavily relies on analog characteristics (Unlike other games such as Perfect Dark and Pokémon Yellow), which differ from unit to unit. The buzzing sound also happens on my CGB, but it's not as noticeable as on SameBoy. I recently did slightly improve on this aspect, but there's still work and research to be done.

**Comment by Pixelnarium** [comment]
It's the same with the game "Tarzan" for GameBoy Color. Buzzing in the intro, menu and the game itself. Gambatte does not seem to have this problem.

**Comment by creambits** [comment]
Remove this line to fix buzzing (Cannon Fodder, Tarzan)
https://github.com/LIJI32/SameBoy/blob/master/Core/apu.c#L772

**Comment by LIJI32** [comment]
While removing this line *will* solve this bug, it's not a correct solution and will break other scenarios. I'm pretty sure I understand how to correctly solve all those mixing related issues that cause buzzing and missing samples, but research is required to verify it first.
