### ISSUE TITLE
Gamepad controller ?

### ISSUE THREAD

**Issue by azoreseuropa** [LIJI32/SameBoy#9]
Will we be able to use this emulator with gamepad controller ?  I love the PS4 controller and hope to be able to use it with your awesome emulator soon. Sorry about my English.

**Comment by LIJI32** [comment]
Hey, are you using the Windows/SDL version or the Mac/Cocoa one?

**Comment by azoreseuropa** [comment]
Hi, thanks for replying asap. I have a MacOS.

**Comment by LIJI32** [comment]
I'll see if I can get it into SameBoy 0.10, the Objective C APIs are only compatible with a few select controllers (the PS4 one is not among them), so I don't know how long it might take. At the worst case, it will be available by 0.11.

**Comment by azoreseuropa** [comment]
No worries. Take your time but I hope that PS4 is one of them.. Will you ? Perhaps 0.11 ? I don't care for how long as long as PS4 controller is available in the near future. Your emulator is an excellent accurate program. Please select PS4 as one of a few select controllers if you can. It's easy and comfortable to use. :)

**Comment by hyarsan** [comment]
Your English is near perfect. 👌 I recommend the LibRetro core if you want to use controllers. https://www.libretro.com/

**Comment by azoreseuropa** [comment]
Why, thank you, hyarsan. 👍
