### ISSUE TITLE
Zen - Intergalactic Ninja (U) graphics glitch

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#90]
during the intro the alien head you can only see from his nose upwards
you are supposed to see from his neck upwards

**Comment by creambits** [comment]
Game breaks starting here
https://github.com/LIJI32/SameBoy/commit/cbbaf2ee843870d96e72380e2dedbdbda471ca76

**Comment by endrift** [comment]
This is a window bug. Similar to https://github.com/mgba-emu/mgba/issues/1519.

**Comment by endrift** [comment]
The bug appears to be because the game turns on the window, then sets wx, then wy, all while in mode 0. However, the wy before resetting it is less than ly, so it in theory is within the window for a few cycles before wy is updated. Being in mode 0 has weird effects on wx/wy interactions it seems.

**Comment by LIJI32** [comment]
Fixed on master with the new window implementation.
