### ISSUE TITLE
Worms Armageddon (E) (M6) [C][!] missing background

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#91]
choose quick game and the background is missing

**Comment by creambits** [comment]
It was working for official 0.11 release
https://github.com/LIJI32/SameBoy/commit/d9dfbcd199949e8ca28751150a91d68768d88273

but broke right afterward due to this
https://github.com/LIJI32/SameBoy/commit/47a74cb6c389ea15682116923b8bcbd4b0389fd1

**Comment by LIJI32** [comment]
If this is true, this means Worms Armageddon depends on uninitialized RAM. I'll have to look into it.

**Comment by creambits** [comment]
```
bgb trace

R014:5669 ld a,(D6F1)
R014:566c cp a,05
R014:566e jr z,5688

2:d6f1 = wra2 (ff70 = 2)
```
It appears this memory area is not pre-written to and affects the scrolling message at the top bar. Bad random values create crashes and glitchy texts.


Latest bgb works okay. ram dump of 2:d000-dfff. Always reverts to these same values on reset.
https://github.com/creambits/RetroArch/blob/temp/2_d000.dump.bin?raw=true

**Comment by trinemark** [comment]
Worms and Marvin share same bug. When you run both games through the official Nintendo bios, they both work without problem in latest git. https://github.com/LIJI32/SameBoy/commit/a62541e57798d64149077c23399721e1626b9523

1. vram is different. not important to fixing these two.
2080-23f0 should be zero'd, according to bios.

2. wram is different. this is important to fixing both games.
sameboy: 1000-1fff = zero'd. 2000-2fff = random().
nintendo: 1000-1fff = random(). 2000-2fff = a mix of data, with lots of zero's. 

I zero'd out 2000-2fff ram and both games work now, using Sameboy bios.

memory dump
http://s000.tinyupload.com/index.php?file_id=98732658402236769061


Tag:
https://github.com/LIJI32/SameBoy/issues/150
