### ISSUE TITLE
doesn't detect my Logitech Gamepad F310

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#93]
i am using a Logitech Gamepad F310 and when i got to configure it
it doesnt detect any of the directions

**Comment by LIJI32** [comment]
Can you test if the directions work without configuration? Some controllers identify directional inputs as "hats" instead of buttons, so they're not configurable, but are still useable.

**Comment by benderscruffy** [comment]
yep you were correct
