### ISSUE TITLE
We by jumalauta demo freezes up

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#97]
http://www.pouet.net/prod.php?which=53867
near the end of the demo it completely freezes up the emulator

**Comment by creambits** [comment]
Works in bgb 1.5.6
```
00:06ac  00.22 ld a,(c004)
00:06af  00.20 ld d,a
00:06b0  00.12 ld a,(c005)
00:06b3  00.10 ld e,a
00:06b4  00.08 ld hl,0488
00:06b7  00.02 add hl,de
=== lcd irq
00:0048  00.88 jp 1ed3
```

Curiously it breaks in bgb 1.5.7
```
00:06ac  00.22 ld a,(c004)
00:06af  00.20 ld d,a
00:06b0  00.12 ld a,(c005)
00:06b3  00.10 ld e,a
00:06b4  00.08 ld hl,0488
00:06b7  00.02 add hl,de
=== error
00:06b8  00.96 ldi a,(hl)
=== lcd irq
00:0048  00.84 jp 1ed3
```
Using debugger, I avoided running 00:06b8 and sent pc back to 00:06b7 before lcd irq runs. So 00:06b8 is executed after irq is finished. Demo works correctly past the freeze spot.

Now what's more interesting is that Sameboy 0.11.1 debugger basically does same thing.
```
->06b7: ADD hl,de
Current line: 0
Current state: Rendering pixel (152/160)
LY: 0
LYC: 0


->06b8: LD a, [hli]
Current line: 0
Current state: Sleeping (0 cycles to next event)
LY: 0
LYC: 0


->06b9 LD b,a
Current line: 0
Current state: Sleeping (8 cycles to next event)
LY: 0
LYC: 0


->0048:  JP $1ed3
```

**Comment by trinemark** [comment]
It gets trapped in a LY loop, waiting for line 153. But it only sees 0-152.
```
16C7  ld a,($FF44)
16C9  cp e
16CA  jr nz, 16C7
```

https://github.com/LIJI32/SameBoy/blob/master/Core/display.c#L930

For DMG mode, it breaks out if we add 1 more cycle.
```
GB_SLEEP(gb, display, 14, (gb->model > GB_MODEL_CGB_C)? 4: 6+1);
```

Although I also wonder if it could be some other issue. Like $FF44 being updated mid-opcode cycle or something.

**Comment by benderscruffy** [comment]
freezes up on real hardware
